### ISSUE TITLE
Getting country international prefix by country code exmple for us +1 or IL +972 etc

### ISSUE THREAD

**Issue by ihabhamad** [Propaganistas/Laravel-Phone#101]
Prior to filing a bug, please check the origin of the unexpected behavior you're facing. Any issues that do not follow this guide will be closed without notice.

1. First try to reproduce the bug in the demo application (https://laravel-phone.herokuapp.com). If all works well, go to step 3.
	
2. Still seeing unexpected behavior? Congratulations, you've possibly found a bug! Please go ahead and create an issue. Describe clearly what you're trying to achieve, along with some erroneous phone numbers and full validation parameters.

3. Try to reproduce the bug in libphonenumber's demo (https://giggsey.com/libphonenumber) and take note of the `isValidNumber()` and `isValidNumberForRegion()` results. If all works well, go to step 5.

4. Still seeing unexpected behavior? Please open an issue at libphonenumber (https://github.com/giggsey/libphonenumber-for-php).

5. This isn't a bug in the package nor in libphonenumber. Fix your own code.

**Comment by ihabhamad** [comment]
thanks, pro but I need country prefix without passing a valid phone number, for example, I want country prefix code by using country code (us country code well return +1) for example without passing the phone number

**Comment by ihabhamad** [comment]
$prefix = phone(null, 'PS')->getPhoneNumberInstance()->getCountryCode(); return error The phone number supplied was null.
$prefix = phone('', 'PS')->getPhoneNumberInstance()->getCountryCode(); return error The string supplied did not seem to be a phone number.

**Comment by ihabhamad** [comment]
my friend I found that on giggsey/libphonenumber-for-php
please add a helper function to call it is very important 
$prefix = \libphonenumber\PhoneNumberUtil::getInstance()->getCountryCodeForRegion('PS');

**Comment by Propaganistas** [comment]
No helper function required if you can get it that way. Just use that code directly.

**Comment by ihabhamad** [comment]
ok my friend but your package is very very useful and if get to it more functionality it will be a perfect package

**Comment by HasanAlyazidi** [comment]
> ```
> $prefix = phone($number, $country)->getPhoneNumberInstance()->getCountryCode();
> ```

Good, but this would be better:
```php
$prefix = phone($number, $country)->getCountryCode();
```

Thank you
