### ISSUE TITLE
Failing phone formats

### ISSUE THREAD

**Issue by nikklass** [Propaganistas/Laravel-Phone#102]
Hi guys,

Am having aproblem validating Kenyan phone numbers esp those starting with these:
25475XXXXXXX. Apparently these are new number formats that were added by a Kenyan mobile phone operator Safaricom. Any ideas on solving this?

**Comment by nikklass** [comment]
The phone numbers seem to validate well on libphonenumber:
https://giggsey.com/libphonenumber/?phonenumber=254757953698&country=KE&language=&region=
returns valid responses. Any known issues here?

**Comment by nikklass** [comment]
Or better still, how do i update so that my installation uses the latest version of giggsey/libphonenumber-for-php? It seems like am using an older version.

**Comment by Propaganistas** [comment]
It's validating just fine.

![Laravel-Phone validator](https://imgur.com/tASxR0A.png)
