### ISSUE TITLE
Incorrect error "Country specification for number [number] required"

### ISSUE THREAD

**Issue by kohenkatz** [Propaganistas/Laravel-Phone#103]
I am using the following validation rule in my application:

```
'phonenumber'     => ['required', 'phone:AUTO,US', 'unique:registered_phones,phonenumber' ]
```

In order to use the `unique` part, I need to make sure that the phone number is E.164 formatted since that is how I store it in the database. Otherwise, someone entering a number in US format that is already in the database would pass validation and then fail insertion (after it is converted to E.164).

To make this work, I use Laravel's `FormRequest#validationData` method like this:

```
protected function validationData()
{
	$data = $this->all();

	// Need to use 'isset' to show the proper error message if the field is left blank
	// Otherwise, the line below throws a `libphonenumber\NumberParseException`
	if (isset($data['phonenumber'])) {
		$data['phonenumber'] = PhoneNumber::make($data['phonenumber'], 'US')->formatE164();
	}

	return $data;
}
```

However, this gives me a problem when the phone number is invalid. If I enter `+15555555555`, I expect to simply get an "invalid phone number" error (or something similar to that). Instead, the error I get is `Country specification for number "+15555555555" required.`

Of course, as you can see, this is not actually the error because I *have* provided the country code `US` in the `PhoneNumber::make` call.

I traced this issue to [`PhoneNumber::filterValidCountry`](https://github.com/Propaganistas/Laravel-Phone/blob/bc07f20b1419b601977c2a8f4e21620af472d3c1/src/PhoneNumber.php#L258-L264), which throws this error about not having specified a country even though the country actually has been specified, just because the number is not valid.

I think that if a single country has been specified, either using `+CountryCode` at the start of the number or passed in as an argument, this error should really say something like "Phone number not valid for country code 'US'".

**Comment by Propaganistas** [comment]
Thanks for reporting. Implemented.

**Comment by kohenkatz** [comment]
That looks great! Thank you!
