### ISSUE TITLE
Latest releases missing in packagist

### ISSUE THREAD

**Issue by dtvmedia** [Propaganistas/Laravel-Phone#104]
Hey, thanks for adding laravel 5.8 support so quickly, but unfortunately it seems packagist isn't picking up the 2 latest versions. For me the latest published version is still 4.1.0 or am i missing something?

**Comment by stojankukrika** [comment]
👍 agree - I have same problem.

**Comment by stojankukrika** [comment]
Test was failed that is the reason why we can't get last version over composer
https://travis-ci.org/Propaganistas/Laravel-Phone/jobs/498396825

**Comment by Propaganistas** [comment]
Builds are green again and Packagist is up to date.
Seems I forgot to reinstate Packagist's connection to GitHub after the service deprecation.

Thanks 👍

**Comment by stojankukrika** [comment]
Thank you @Propaganistas for updates!
