### ISSUE TITLE
NULL results in exception

### ISSUE THREAD

**Issue by lasseeee** [Propaganistas/Laravel-Phone#105]
It blows up on `(string) PhoneNumber::make(null)`:

```
ErrorException (E_RECOVERABLE_ERROR)
Method Propaganistas\LaravelPhone\PhoneNumber::__toString() must return a string value
```

Is that how it's supposed to behave?

**Comment by lasseeee** [comment]
PHP 7.3.2
Laravel 5.8.3 (fresh install)
Propaganistas/Laravel-Phone 4.1.2

Open `php artisan tinker` and run
```
(string) Propaganistas\LaravelPhone\PhoneNumber::make(null);
```
 to reproduce.

**Comment by Propaganistas** [comment]
Fixed.
