### ISSUE TITLE
Cannot recognize number: Number does not match the provided country

### ISSUE THREAD

**Issue by mshifo** [Propaganistas/Laravel-Phone#106]
Hello team,

First of all thank you so much for this amazing library :+1: 

Here is my problem :

this my validation rule in my project :
$rules['attributes.patient_mobile_number'] = 'required|phone:AUTO,EG,mobile';

it works for most numbers but didn't recognize Yemeni number (009677786XXXX)  and it is correct number and i got this message : Number does not match the provided country.

I noticed that it accepts it when adding extra digit, but this number is correct 

Thank you so much for your help !

**Comment by Propaganistas** [comment]
Did you carry out step 3 in the issue template?

>>> Try to reproduce the bug in libphonenumber's demo (https://giggsey.com/libphonenumber) and take note of the `isValidNumber()` and `isValidNumberForRegion()` results

Furthermore: I cannot help when you're obfuscating the number.

**Comment by mshifo** [comment]
isValidNumberForRegion() = false 
isValidNumber()  =  false

Number : 0096777866463

**Comment by Propaganistas** [comment]
Since both validations return false, the number itself is not correct according to https://giggsey.com/libphonenumber. There's nothing I can do here.

**Comment by simioluwatomi** [comment]
So I'm getting this error on a phone number. Problem is that I am not validating the phone number. Does the ```make``` method try to validate the phone number being passed to it?

```
PhoneNumber::make($this->next_of_kin_phone_number, 'NG')->formatE164();
```
After running [libphonenumber](https://giggsey.com/libphonenumber) on the number throwing this error, I get the following

```
isPossibleNumber() => true,
isValidNumber() => false,
isValidNumberForRegion() => false,
getRegionCodeForNumber() => NG,
getNumberType() => UNKNOWN
```

Like the code shows, I'm not trying to validate a number, only want to format it in international format

**Comment by Propaganistas** [comment]
The formatter only works with valid numbers. The number you supplied is invalid according to libphonenumber, hence formatting fails.

FYI: Don't hijack closed issues.
