### ISSUE TITLE
Validation rule does not exist

### ISSUE THREAD

**Issue by pentacore** [Propaganistas/Laravel-Phone#107]
When trying to use the validation part of the lib i get either "The method validatePhone does not exist" or "Rule::phone() Does not exist".

Using the helper function however, works.

Laravel 5.8.5
PHP 7.3

Tried: 
- with the provider class included and without it.
- Reinstalling, Clearing composer cache
- Clearing laravel cache, compiled and optimizing
- dump-autoload
- Staring into the mirror stating "validatePhone" Three times whilst turning around

**Comment by Propaganistas** [comment]
This appears to be a composer cache issue since `validatePhone` is an old method of v2. Other users have also experienced this in the past: #11 , #74

**Comment by pentacore** [comment]
Yea, i saw those.

Considering i just installed this lib for the first time, it shouldnt be in my cache, and since i cleared my composer cache (Since i saw those other issues) and did a full reinstall, which still didnt fix it.

Or were you referring to an upstream cache?

Im unsure as to what to do at this point if im going to be honest.

**Comment by pentacore** [comment]
Composer reports that v4.1.3 is installed, i cant find any reference to validatePhone in the lib

**Comment by Propaganistas** [comment]
I'm highly clueless as well. Perhaps try installing by commit hash or fixed version, and then run composer update?

**Comment by pentacore** [comment]
same issue with dev-master im afraid

**Comment by pentacore** [comment]
I managed to solve it somehow..
I dont know where or how, but it seems an older version got cached somewhere inside of my docker container. (Which is strange, since i installed 4.1.3 specifically when installing the lib, and i've got the entire project folder mounted as the web root)

But after re-deploying the container the validator seems to be working.

**Comment by cja-github** [comment]
In case this helps someone else: I had this error but my problem was that I had copied the Nova field definition from a project that had propaganistas/laravel-phone installed to a project that didn't have propaganistas/laravel-phone installed. And then I was searching my code for validatePhone, wondering why I wasn't finding anything! Hopefully this message will save someone else from repeating my hour of confusion.
