### ISSUE TITLE
Validation passes for illegal Strings

### ISSUE THREAD

**Issue by TNChalise** [Propaganistas/Laravel-Phone#109]
I have been trying to validate phone numbers by defining regions of countries.
 Input Field is:
```
[
    'field' => '0418916818tho as'
]
```
And the server side validation rules are:
```
[
    'field' => 'phone:AF,AL,DZ,AD,AO,AI,AQ,AG,AR,AM,AW,AU,AT,AZ,BS,BH,BD,BB,BY,BE,BZ,BJ,BM,BT,BO,BA,BW,BV,BR,IO,BN,BG,BF,BI,KH,CM,CA,CV,KY,CF,TD,CL,CN,CX,CC,CO,KM,CG,CK,CR,HR,CU,CY,CZ,DK,DJ,DM,DO,EC,EG,SV,GQ,ER,EE,ET,FK,FO,FJ,FI,FR,GF,PF,TF,GA,GM,GE,DE,GH,GI,GR,GL,GD,GP,GU,GT,GN,GW,GY,HT,HM,HN,HK,HU,IS,IN,IM,ID,IR,IQ,IE,IL,IT,CI,JE,JM,JP,JO,KZ,KE,KI,KP,KR,XK,KW,KG,LA,LV,LB,LS,LR,LY,LI,LT,LU,MO,MK,MG,MW,MY,MV,ML,MT,MH,MQ,MR,MU,MX,FM,MD,MC,MN,ME,MS,MA,MZ,MM,NA,NR,NP,NL,AN,NC,NZ,NI,NE,NG,NU,NF,MP,NO,OM,PK,PW,PS,PA,PG,PY,PE,PH,PN,PL,PT,PR,QA,RE,RO,RU,RW,KN,LC,VC,WS,SM,ST,SA,SN,RS,SC,SL,SG,SK,SI,SB,SO,ZA,GS,SS,ES,LK,SH,PM,SD,SR,SJ,SZ,SE,CH,SY,TW,TJ,TZ,TH,TG,TK,TO,TT,TN,TR,TM,TC,TV,UG,UA,AE,GB,US,UM,UY,UZ,VU,VA,VE,VN,VG,VI,WF,EH,YE,ZM,ZW'
]
```

The validation passes through it. I know, it is hard to investigate through all country codes specified. Is there any wild card method to validate international phone numbers by selecting range of countries ?

As per documentation, I think I will be able to validate country types specified in ISO 3166-1 alpha-2 compliant country codes.

**Comment by Propaganistas** [comment]
Some countries (such as the US) accept A-Z characters. Your phone number string will probably just happen to validate correctly for such countries. That's the tradeoff you make when accepting that many countries.

**Comment by Propaganistas** [comment]
It appears Germany (DE) passes validation for this phone number.

**Comment by Propaganistas** [comment]
Also: https://github.com/googlei18n/libphonenumber/blob/master/FAQ.md#why-does-the-library-treat-some-non-digit-characters-as-digits

**Comment by TNChalise** [comment]
My Bad.. Never went that deep on FAQ.
