### ISSUE TITLE
Method [validatePhone] does not exist

### ISSUE THREAD

**Issue by gregoryduckworth** [Propaganistas/Laravel-Phone#11]
When adding in the phone validation to my rules I get the following exception:

BadMethodCallException in Validator.php line 2615:
Method [validatePhone] does not exist.

**Comment by Propaganistas** [comment]
Which version are you using?

**Comment by gregoryduckworth** [comment]
I am using 2.2.0 and then I have added ```'Propaganistas\LaravelPhone\LaravelPhoneServiceProvider'``` to the config. 

I'll see if I can gather any more information today about it.

**Comment by gregoryduckworth** [comment]
Retried again this morning after removing the dependencies and clearing the cache and this issue seems sorted now and I am unable to replicate.

**Comment by Propaganistas** [comment]
Glad you sorted it out.
Probably a cache issue :-)
