### ISSUE TITLE
Crashes with exception instead of returning with error message

### ISSUE THREAD

**Issue by lasseeee** [Propaganistas/Laravel-Phone#110]
When submitting a non-valid phone number, the app returns the following exception:

`ErrorException (E_ERROR) Number does not match the provided country.`

Instead of just returning the validation message in the form.

Am I missing something?

**Comment by Propaganistas** [comment]
As requested in the issue template: additional info is needed. Your question is too generic. Which version, which number and country are you using, code samples, ...

**Comment by Propaganistas** [comment]
Can you reproduce on the demo?

https://laravel-phone.herokuapp.com/

**Comment by lasseeee** [comment]
Tried this on a Laravel 5.7.17 using laravel-phone 4.1.3 with the validation rule:

```
'phone_number' => [
                'nullable',
                'phone:NO,mobile',
                Rule::unique('participants'),
    ],
```

crashes when posting for example 22222222 (which is landline).

**Comment by Propaganistas** [comment]
I cannot reproduce. Validation just returns false as expected. I suspect you've got some other call while rendering the page (for example the phone helper) that's causing the exception.

**Comment by lasseeee** [comment]
You're right, there was a call upon re-rendering the form. Thanks for helping me track down the bug. Stellar package!
