### ISSUE TITLE
Ambiguous phone validation parameter: "mobile". This parameter is recognized as an input field and as a phone type. Please rename the input field.

### ISSUE THREAD

**Issue by J5Dev** [Propaganistas/Laravel-Phone#111]
When trying to validate a mobile number, we receive the following error:

"Ambiguous phone validation parameter: "mobile". This parameter is recognized as an input field and as a phone type. Please rename the input field."

What we have:

Laravel Version: 5.7
Package Version: 4.1.3

```
'mobile'    => [
    'nullable',
    Rule::phone()->detect()->country('GB')->type('mobile'),
    'max:35'
],
```

Whilst I can see that this is slightly covered within issue #60 the (non) solution of changing our field name isn't one I can see as viable.

This is the field name used on all our forms, within our api, and of course is the name of the column within our DB (and subsequent Model properties).

Is there a way to allow/cater for the column name, without us having to refactor huge amounts of our application... just to suit validation?

Nothing in the documentation identifies how this can be done, nor does it state certain field names are not available to be used. Which seems correct, as surely it shouldn't be relevant what a field name is when validating it.

**Comment by Propaganistas** [comment]
Fair point. I've updated the Rule class to already resolve number types passed as text instead of offloading this to the validator.
