### ISSUE TITLE
Error validate number country VietNamese (VN)

### ISSUE THREAD

**Issue by tbdavid94** [Propaganistas/Laravel-Phone#116]
I use phone number is 0862049456 test but return false although it is active

Pls support for me. Thanks team

**Comment by tbdavid94** [comment]
![Screenshot from 2019-05-15 10-09-21](https://user-images.githubusercontent.com/31137542/57745988-8ca3f380-76f9-11e9-9310-82afd2b503b9.png)

**Comment by Propaganistas** [comment]
Function | Value
--- | ---
isPossibleNumber() | true
isValidNumber() | false
isValidNumberForRegion() | false

The number isn't valid according to libphonenumber.
