### ISSUE TITLE
Why is there an strtolower on rule parameters?

### ISSUE THREAD

**Issue by wfeller** [Propaganistas/Laravel-Phone#117]
Hey,

Is there a reason to strtolower on the parameters in https://github.com/Propaganistas/Laravel-Phone/blob/f65d4e68e3200bfa40e83c92a33db5eeada78f29/src/Validation/Phone.php#L104 ?

It breaks validation when you use capital letters.

This fails:
```php
$data = [
    'Telephone' => '01 11 11 11 11',
    'Telephone_Country' => 'fr',
];

$rules = ['Telephone' => 'phone:Telephone_Country'];

Validator::make($data, $rules)->passes() ? 'Success' : 'Failure';
```

While this does not:
```php
$data = [
    'telephone' => '01 11 11 11 11',
    'telephone_country' => 'fr',
];

$rules = ['telephone' => 'phone:telephone_country'];

Validator::make($data, $rules)->passes() ? 'Success' : 'Failure';
```

Thanks

**Comment by Propaganistas** [comment]
Thanks for filing this. Seems like a bug indeed. Fixed in the most recent version.
