### ISSUE TITLE
it work in my localhost laptop but notwork in server !!!

### ISSUE THREAD

**Issue by vahidalvandi** [Propaganistas/Laravel-Phone#119]
i use sample code
`			 echo PhoneNumber::make('09128300001')->ofCountry('IR');`
return The connection was reset
![image](https://user-images.githubusercontent.com/7871623/58093113-0bf66300-7be3-11e9-861e-e8d7bd047d00.png)

**Comment by vahidalvandi** [comment]
i use laravel 5.5 and php7 and laravel-phone 4.1

**Comment by Propaganistas** [comment]
Nothing to do with this package or Laravel as a whole.

**Comment by vahidalvandi** [comment]
do is connect web server ?

**Comment by Stanislas-Poisson** [comment]
Hi. Have you look to your log ? laravel.log maybe some information was logged in ;)

**Comment by vahidalvandi** [comment]
noting exists !!

**Comment by MahmoudSaidHaggag** [comment]
This happened to me as well
Can help me??
