### ISSUE TITLE
weird CA phone number validation

### ISSUE THREAD

**Issue by michaelnguyen547** [Propaganistas/Laravel-Phone#121]
The number I tested is `117802225555`. This number has two 1's in the front - with a total of 11 digits. A correct number should be `17802225555`(10 digits). 

This package and libphonenumber(https://github.com/giggsey/libphonenumber-for-php) think the `117802225555` is a valid phone number. I think it is an invalid phone number.

**Comment by Propaganistas** [comment]
If libphonenuber flags it as valid, head over to that repository.
