### ISSUE TITLE
Laravel 6 Support

### ISSUE THREAD

**Issue by alphametric** [Propaganistas/Laravel-Phone#122]
The package needs to be updated to support Laravel v6 (specifically because of composer dependencies)

**Comment by alphametric** [comment]
Sorry, I see there's a v6 branch already. Thanks!

**Comment by simioluwatomi** [comment]
When will the Laravel 6.0 version be released? My update to Laravel 6 is failing because of this package

**Comment by alphametric** [comment]
Version 6 of Laravel is not due for release till September 3rd. There is a v6 branch of the package, so I’d imagine it will be available soon.

**Comment by simioluwatomi** [comment]
> As I'm unable to do any work before Sept **5th**, feel free to send a well tested PR on the V6 branch.

What would this PR look like? I'd love pointers because I've never contributed code to an OSS before? Thanks

**Comment by alphametric** [comment]
Unfortunately, I don't have the time do a PR, but it looks like all that needs to be done is to adjust the composer dependencies of `illuminate/support` and `illuminate/validation` to allow for version 6 of the framework.

Beyond this though, it appears that some refactoring needs to be done with the test suite as it makes extensive use of deprecated PHPUnit methods which will be removed in v9.

**Comment by stojankukrika** [comment]
L v6 is just released :) hope that we get update soon ;)

**Comment by Propaganistas** [comment]
See #124

**Comment by Propaganistas** [comment]
New release has been created. You can update to `4.2.2`.

**Comment by stojankukrika** [comment]
👍
