### ISSUE TITLE
How can i get country dial code from full mobile number like +91XXXXXXXXXX

### ISSUE THREAD

**Issue by arvind2503** [Propaganistas/Laravel-Phone#127]
I am using this package in laravel. I am getting full mobile with country code. I want to extract country dial code from given number. 

I am getting country code using below code. 

$country_code = (string) PhoneNumber::make($post_data['data']['mobile'])->getCountry();  
// Getting IN/US etc. 
How i can get country dial code like +91 , +1

**Comment by Propaganistas** [comment]
Use `getPhoneNumberInstance()` to get to the `libphonenumber` object. I suspect it has some sort of method to extract the dial code.

**Comment by AnasSafi** [comment]
`use Propaganistas\LaravelPhone\PhoneNumber;`

```
$phoneNumber =  PhoneNumber::make("+970598123456")->getPhoneNumberInstance();

$phoneNumber->getNationalNumber();
$phoneNumber->getCountryCode(); //here what you need
```

**Comment by lvandyk** [comment]
> `use Propaganistas\LaravelPhone\PhoneNumber;`
> 
> ```
> $phoneNumber =  PhoneNumber::make("+970598123456")->getPhoneNumberInstance();
> 
> $phoneNumber->getNationalNumber();
> $phoneNumber->getCountryCode(); //here what you need
> ```

Legend!! Thank you.

**Comment by RobinGnosco** [comment]
This doesn't seem to work anymore - is there a new way to get the country code?

**Comment by 7adidaz** [comment]
> This doesn't seem to work anymore - is there a new way to get the country code?

You need to convert the phone instance into a lib phone object using toLibPhoneObject. Once you do that, the mentioned methods should work, like this:

```
$phoneNumber = (new PhoneNumber("+970598123456"))->toLibPhoneObject();

$phoneNumber->getNationalNumber(); // outputs: 598123456
$phoneNumber->getCountryCode(); // outputs: 970
```
