### ISSUE TITLE
check if 839 area code is supported

### ISSUE THREAD

**Issue by stojankukrika** [Propaganistas/Laravel-Phone#128]
Hi,
I am not from US and didn't have this phone number, but findout it...can you tell me is that library can validate this phone number:
https://www.t-mobile.com/coverage/SC-803-area-code-overlay-notification

Regards

**Comment by stojankukrika** [comment]
👎 for your closing without any word!

**Comment by Propaganistas** [comment]
Try and see... I don't know. As stated in both the README and the issue template: the package uses `libphonenumber` under the hood.
