### ISSUE TITLE
Nullable rule is ignored, still trying to validate = libphonenumber exception

### ISSUE THREAD

**Issue by martinsnajdr** [Propaganistas/Laravel-Phone#139]
I'm using this library in the most basic form inside my custom form request class (everything is up to date):
`nullable|phone:CZ`

It should try to validate the phone number only if it's not null. But it actually throws a libphonenumber exception `The phone number supplied was null.`

Which means it ignores the nullable and it's still trying to validate the number using the libphonenumber library. I cannot reproduce it using https://laravel-phone.herokuapp.com, because everytime I put my rules into the field, the nullable rule is stripped down and I have to put a phone number in the field to trigger the validation. If I put required (instead of nullable), it displays the right required validation message, but I need the field to be optional.

I don't have any other validation using libphonenumber inside my app / or any other implementation of this library (except laravel-phone) in my app.

**Comment by Propaganistas** [comment]
I'm afraid I can't reproduce on a fresh install:

![Schermafbeelding 2020-03-14 om 21 17 51](https://user-images.githubusercontent.com/6680176/76689744-5137c580-6639-11ea-88f3-5dc110d8c5e2.png)
