### ISSUE TITLE
Outdated mobile codes?

### ISSUE THREAD

**Issue by Sky7ure** [Propaganistas/Laravel-Phone#140]
Greetings,

Is Wikipedia up-to-date with mobile phone codes? It lists that **561**, for example, is a code provided to new customers by Turkcell...

However, `Rule::phone()->country('TR')->mobile()` doesn't pass with a number that begins with it! It passes for some other codes though, such as **533**, for instance!

If Wikipedia is outdated, where should I check to make sure that validation is up-to-date with the currently provided and supported mobile codes in a country?!

Thank you.

**Comment by Propaganistas** [comment]
Wikipedia is never, ever, to be considered as a source of truth.

This package uses [Google's `libphonenumber`](https://github.com/google/libphonenumber) library under the hood. I'm not aware myself of the actual valid or invalid telephone codes.

**Comment by Sky7ure** [comment]
Thank you kindly for the confirmation.
