### ISSUE TITLE
Numbers with characters passed validation

### ISSUE THREAD

**Issue by jonyking** [Propaganistas/Laravel-Phone#141]
Hello,

I tried the following phone number for germany `+4917661058532`. The validation is valid. But the validation is also correct if I do the following `+4917661058532s`. Also works in your test laravel project.

<img width="1444" alt="Bildschirmfoto 2020-03-29 um 10 32 06" src="https://user-images.githubusercontent.com/24831213/77844668-bdbdd300-71a8-11ea-8c9e-e98372b3ae9a.png">

**Comment by Propaganistas** [comment]
As per the issue guidelines, check first with libphonenumber:

https://giggsey.com/libphonenumber/?phonenumber=%2B4917661058532s&country=DE&language=&region=

![Schermafbeelding 2020-03-29 om 10 50 37](https://user-images.githubusercontent.com/6680176/77844966-2b6afe80-71ab-11ea-8594-9d18454122e4.png)

The library itself reports `+4917661058532s` as valid. You can always use one of the formatting functions afterwards.

**Comment by Propaganistas** [comment]
Or if you're hesitant to accept this as a valid number, strip alpha characters before validation yourself. The package only exposes libphonenumber's validation capabilities.
