### ISSUE TITLE
"Number requires a country to be specified" error

### ISSUE THREAD

**Issue by nospoon** [Propaganistas/Laravel-Phone#142]
When trying to call any formatting method on PhoneNumber, it throws an error "Number requires a country to be specified".

```phone($number)->formatInternational()```
Throws an error,
```phone($number)``` 
Does not

It should not require you to specify the country, in my use case detecting the country is actually one of the main reasons for using the library.

**Comment by Propaganistas** [comment]
It is virtually impossible for *any* library to reformat an existing (randomly formatted) number without any clue, hence the required country. Lots of countries share phone number formats, so that would be hard without.

You're not limited to passing only 1 country by the way. You can surely pass in multiple countries.

**Comment by nospoon** [comment]
But the parser can already detect the country from the number, so why can't it use that result?

**Comment by Propaganistas** [comment]
I suggest to take a look at the following automated test which I think exactly describes your use case: https://github.com/Propaganistas/Laravel-Phone/blob/master/tests/PhoneNumberTest.php#L89

```
public function it_can_format_international_numbers_without_given_country()
{
    $object = new PhoneNumber('+3212345678');
    $this->assertEquals('012 34 56 78', $object->format(PhoneNumberFormat::NATIONAL));
}
```

As you can see the provided number is in E.164 format as well and doesn't need any additional country specification to reformat. Everything works as designed. So perhaps there's something wrong with the phone number you're using so it can't be autodetected? Or perhaps there's something else going on in your code?
