### ISSUE TITLE
Country code format

### ISSUE THREAD

**Issue by LarryBarker** [Propaganistas/Laravel-Phone#143]
More of a general question here, apologies if this is not the proper forum.

Do country codes have to be the 2-letter ISO code? Anyway to support 3-letter?

Thanks!

**Comment by Propaganistas** [comment]
At this moment the package only supports 2-letter ISO codes indeed. However I think supporting 3-letter codes shouldn't be that hard: https://github.com/Propaganistas/Laravel-Phone/blob/master/src/Traits/ParsesCountries.php#L19

I don't think supporting both formats at the same time is the way to go, but I'm open for a PR in which some sort of config determines the format to use.
