### ISSUE TITLE
Option for fallback country to be provided in class usage.

### ISSUE THREAD

**Issue by yogeshgalav** [Propaganistas/Laravel-Phone#145]
PhoneNumber::make($contact_number);

if $contact_number is in local format then it fails with "Number requires country code to be specified".
if  country code is provided and $contact_number is international it fails with "Number does not match the provided country".

if fallback country code method present, please mention in documentation.

**Comment by Propaganistas** [comment]
Hi

Please refer to the following tests:

https://github.com/Propaganistas/Laravel-Phone/blob/0f4c7bdac33d75d5a937e8ae699e8536463fd6af/tests/PhoneNumberTest.php#L96

This one shows that the fallback country is ignored when a **valid** international phone number was passed.

https://github.com/Propaganistas/Laravel-Phone/blob/0f4c7bdac33d75d5a937e8ae699e8536463fd6af/tests/PhoneNumberTest.php#L248

This one shows that an exception is thrown when the international phone number itself cannot be parsed automatically, and the provided fallback country also didn't rescue the operation.

So as it appears to me your OP is already covered.
