### ISSUE TITLE
Where is my "validation rules array"?

### ISSUE THREAD

**Issue by cja-github** [Propaganistas/Laravel-Phone#148]
I'm new to Laravel so sorry for my ignorance...

https://github.com/Propaganistas/Laravel-Phone#validation says

"To validate a phone number, use the phone keyword in your validation rules array or use the Phone rule class to define the rule in an expressive way."

Please can you tell me where my "validation rules array" is?

I'm also interested to know how to "define the rule in an expressive way", but I suspect I don't need to if I know what the validation rules array is.

P.S. I have read https://laravel.com/docs/7.x/validation but it doesn't clearly identify anything as *the* "validation rules array".

**Comment by Propaganistas** [comment]
Please refer to https://laravel.com/docs/7.x/validation#quick-writing-the-validation-logic

The "validation rules array" is the array you pass for example to the `validate` method.
