### ISSUE TITLE
Pakistani phone numbers are not working

### ISSUE THREAD

**Issue by ismailansari** [Propaganistas/Laravel-Phone#150]
I'm using this in my project and faced this issue then I verified on the demo site and the same issue there
Special characters at the end isn't allowed and same issue if  i pass the invalid phone `+++923326354000???` 
![FireShot Capture 014 - Laravel Phone demo v4 2 4 - laravel-phone herokuapp com](https://user-images.githubusercontent.com/5441541/92025301-c67a8c80-ed78-11ea-9d67-f532fe101e7f.png)

**Comment by Propaganistas** [comment]
See #141 

https://giggsey.com/libphonenumber/index.php?phonenumber=%2B923326354000%3F%3F%3F&country=PK&language=&region=

Libphonenumber itself reports `+923326354000???` as valid. You can always use one of the formatting functions afterwards. Or if you're hesitant to accept this as a valid number, strip special characters before validation yourself. The package only exposes libphonenumber's validation capabilities.
