### ISSUE TITLE
Hello some countries phone number validation is not working like jamaica united king haiti etc

### ISSUE THREAD

**Issue by atta1234** [Propaganistas/Laravel-Phone#156]
please tell me how to solved issue for those countries , 
here is the live url for testing, https://globalmanna.com/registerhow to  customized it for that number what's the step to resovled those issue please

**Comment by Propaganistas** [comment]
https://github.com/Propaganistas/Laravel-Phone#validation

**Comment by atta1234** [comment]
> https://github.com/Propaganistas/Laravel-Phone#validation

please read my question , i have done all that stuff but some countries validation are not working like jamaica united kingdom  here is the live example https://globalmanna.com/register
