### ISSUE TITLE
Hekllo i m having issue with jamaica i dont' see any diffrence of jamaica fixed line and mobile number

### ISSUE THREAD

**Issue by atta1234** [Propaganistas/Laravel-Phone#157]
this website telling me fixed line and mobile number
https://giggsey.com/libphonenumber/index.php?phonenumber=%2B18769574373&country=JM&language=&region=JM
https://giggsey.com/libphonenumber/index.php?phonenumber=876-5557-710&country=JM&language=&region=JM

fixed line failed for alidation
and mobile passed,
but i don't see any difference in both of them author can you please help

**Comment by Propaganistas** [comment]
When I try the fixed line phone number everything is working just fine.

How am I supposed to help if you don't share the actual code you're having troubles with?

**Comment by atta1234** [comment]
try this one with jamaica +18769574373

**Comment by Propaganistas** [comment]
That's working just fine.
![image](https://user-images.githubusercontent.com/6680176/95560133-1d7b1d80-0a19-11eb-8807-e448e1f47c74.png)


Again, if you're not sharing any of your code it's virtually impossible to help.

**Comment by atta1234** [comment]
return Validator::make($data, [
            'phone' => 'phone:code,mobile|phone_unique',
              ],[
            'phone_unique' => 'Phone Number already exists!', // <---- pass a message for your custom validator
              ]);

**Comment by Propaganistas** [comment]
You're using the following configuration:

`phone:code,mobile`

* `mobile`: only accept mobile phone numbers
* `code`: this is expected to be another request input named "code", containing a country code.

So if either the phone number is not a mobile phone OR the country code in `$request->input('code')` is not "JM", then the validation will fail.

All detailed in https://github.com/Propaganistas/Laravel-Phone#validation
