### ISSUE TITLE
Guess country by full number

### ISSUE THREAD

**Issue by andriytkachiv** [Propaganistas/Laravel-Phone#16]
Hi, is there a possibility to validate without country (or guess country) having only full number (e.g. +48570934649)
I need to validate number, but I don't have country field.

For example this frontend libray https://github.com/Bluefieldscom/intl-tel-input  uses Google LibPhoneNumber and could guess country by full number.

**Comment by Propaganistas** [comment]
That's actually a great feature request!

I'll take a look at it when I find some time. PR's always welcome.

**Comment by Propaganistas** [comment]
Hi, seems like I implemented it immediately... :-)

Could you please test the dev-master version and report back so I can roll out a new release?

**Comment by andriytkachiv** [comment]
@Propaganistas  Thanks! That's great! I am testing it right now : ) Will give a feedback very soon!

**Comment by andriytkachiv** [comment]
@Propaganistas  Doesn't work for number +48570934111 (Polish)
It's valid, E164 formatted number
I received error 'AUTO'

**Comment by Propaganistas** [comment]
Did you define the validator rule as `phone:AUTO` ? (new README entry)
Plugging that phone number in the PhpUnit tests seems to work...

**Comment by andriytkachiv** [comment]
I am very sorry I didn't properly update library :)
Now it works!
Thanks!

**Comment by Propaganistas** [comment]
New release rolled out.

Please update to 2.4.0 using `composer require propaganistas/laravel-phone ~2.4`

**Comment by Braunson** [comment]
Is there an easy way to check this using the Utility and not validation?

i.e.

```
\Propaganistas\LaravelPhone\PhoneNumber::make('845-260-8095')->isOfCountry('CA'))
```

That seems to throw a `Number requires a country to be specified`. I just don't know the numbers country and either want to know what it is OR know if it's is or is not of Country specified.
