### ISSUE TITLE
On install package it work in my localhost But on the server it stop the all app

### ISSUE THREAD

**Issue by MahmoudSaidHaggag** [Propaganistas/Laravel-Phone#161]
On install package it work in my localhost But on the server it stop the all app

can help me please?
i using laravel 8

**Comment by Propaganistas** [comment]
Uninstall the package on your server and see if the app still stops. Since it's just working for millions of others, I highly doubt this package is the culprit.

**Comment by MahmoudSaidHaggag** [comment]
Thanks, i am find the problem in another part
