### ISSUE TITLE
How to specify all country codes?

### ISSUE THREAD

**Issue by davide-casiraghi** [Propaganistas/Laravel-Phone#166]
I'm creating a website where I need to accept phone numbers from all over the world.   
So I have to verify if the phone number added by the user corresponds to the standard of at least one country.   

Is there a simple way to specify all countries in the validation rules?

**Comment by Propaganistas** [comment]
No, there's really no way to do this (and you shouldn't want to).  There are over 180+ countries in the world, and each country has a vast set of their very own number rules. A weird phone number like "1234" or even "12ab34" may be perfectly valid somewhere in the world.. 

Ultimately the input would behave just like a plain text input without constraints. 

There's no point in "validating" a phone number if you don't give any pointers where to validate against.

**Comment by Propaganistas** [comment]
Why not asking your users for the country their phone number originates from, just like any other global website...?

![image](https://user-images.githubusercontent.com/6680176/103012106-5c5e4100-453b-11eb-883e-3667c4ae9f1d.png)

**Comment by davide-casiraghi** [comment]
Thanks for the advice, 
this is a great idea.

**Comment by dreammonkey** [comment]
Does anyone know where to get this list ?

Country + abbreviation + phone number prefix ?
