### ISSUE TITLE
German Number For Fax on a PC not valid

### ISSUE THREAD

**Issue by cfreak** [Propaganistas/Laravel-Phone#17]
I try to validate this number +4989620603291873  but it fails, but the fax number is valid and exists.

Is there anything i can do, to get it validated.

**Comment by Propaganistas** [comment]
Hi

The specified number even fails on Google's original libphonenumber library (which this package simply implements), so I suggest you open an issue in their queue to get this resolved.

https://github.com/googlei18n/libphonenumber
