### ISSUE TITLE
Validation pass if the phone with indicator and 0

### ISSUE THREAD

**Issue by mouadaarab** [Propaganistas/Laravel-Phone#170]
Laravel : 7.*
Rule : phone:FR

I try to validate this data: +330661728390 and the validation passes

There is any solution to refuse this validation

**Comment by Propaganistas** [comment]
It's perfectly valid according to Google:

![image](https://user-images.githubusercontent.com/6680176/109499264-efb07700-7a94-11eb-8d88-a56230497853.png)
