### ISSUE TITLE
Localization support

### ISSUE THREAD

**Issue by jevail** [Propaganistas/Laravel-Phone#173]
Would love to see localization support for this package

**Comment by Propaganistas** [comment]
Please elaborate.

**Comment by jevail** [comment]
Would be nice if validation errors could be localized. I tried publishing the vendor package so i could change the validation messages my self, but this could not be done.
Maybe there is another way to localize these validation messages. If so, it would be very handy if this was found in the Readme file :)

**Comment by Propaganistas** [comment]
Just add a line the `validation.php` language files:

```php
'phone' => '--- Your localized validation message ---',
```
