### ISSUE TITLE
Objects not serializable when no country detected

### ISSUE THREAD

**Issue by smares** [Propaganistas/Laravel-Phone#177]
Serializing PhoneNumber objects fails with phone numbers that are not fully qualified and do not have a country because E164 formatting throws an exception.

Would it make sense to serialize using the raw number in such cases?

**Comment by Propaganistas** [comment]
Tough question. Given the current opinionated implementation it would certainly break stuff somewhere in devland. That's why the provided casts offer both choices explicitly (raw number or E.164).

Can you elaborate on the specific use case of serializing unqualified phone numbers?

**Comment by smares** [comment]
It's no biggie for me, noticed this behavior while trying to serialize own classes with PhoneNumber properties populated by an API call where some numbers have only a city prefix.

I was able to solve the issue in my special case by having my own classes implement Serializable as well. In case I don't have a fully qualified number, I serialize the PhoneNumber properties using the raw number.

**Comment by Propaganistas** [comment]
It might be useful to revisit the implementation nonetheless.

In the end serialization is all about being able to deserialize back into a property-filled object... The question I'm wondering about (but tend in answering "no") is if there's a useful case for serializing an unqualified object. Put plainly, the object would just be a transparent wrapper for a raw number in that case with no additional properties filled in?

Or we could even consider this from another point of view: if the PhoneNumber class is somehow meant to always operate on qualified numbers, should the existence of unqualified instances be prevented?

I'd love your opinion on this.

**Comment by smares** [comment]
> Or we could even consider this from another point of view: if the PhoneNumber class is somehow meant to always operate on qualified numbers, should the existence of unqualified instances be prevented?

In my special case, the current implementation allows me to use PhoneNumber as wrapper for any phone number coming from an API and deal with turning it into a FQN later without requiring a temporary string property or defining the type as `PhoneNumber|string`.

My scenario is the following: I have several model classes that each represent an entity coming from an API service. The service that talks to the API takes the API response, JSON-decodes it to a `stdClass` and returns a new model class instance passing the decoded `stdClass` to its constructor. The model class iterates over every property of the `stdClass` and assigns the value to its own property but casts that value to another type if it has to with the help of Reflection and some custom PHP 8 property attributes. This "how to turn a stdClass into a Company or Customer model" is handled in a base class which all my model classes extend.
The way PhoneNumber works now basically allows my base class to turn the properties e.g. `phoneNumber` and `faxNumber` from string to a PhoneNumber object and the extending class can later deal with the numbers itself in its constructor after all other properties have been set. It can then check if the number already is fully qualified and if not, look in a `country` property for example and reassign `$phoneNumber = $phoneNumber->ofCountry($this->country);` for example.

Later in my code, there is no difference for me if I have to do something like this, given the property is of type `PhoneNumber|string`

```
if ($customer->phoneNumber instanceof PhoneNumber) {
  $whatever = $customer->phoneNumber->formatE164()
} else {
  $whatever = $customer->phoneNumber;
}
```

or do this, the way it currently works

```
try {
  $whatever = $customer->phoneNumber->formatE164()
} catch (Exception) {
  $whatever = $customer->phoneNumber->getRawNumber();
}
```
