### ISSUE TITLE
Sri Lanka mobile numbers 074 XXX XXXX

### ISSUE THREAD

**Issue by ManojPrasha9394** [Propaganistas/Laravel-Phone#178]
In Sri lanka now +94 74 XXX XXXX numbers are available
![image](https://user-images.githubusercontent.com/56943590/120295066-6ce1c700-c2e4-11eb-89cd-46cd71b9998f.png)

Can you please update
74 for Dialog mobiles

**Comment by smares** [comment]
The number from your screenshots is valid in both https://laravel-phone.herokuapp.com/ and https://giggsey.com/libphonenumber/?phonenumber=0740169784&country=LK&language=&region=

**Comment by ManojPrasha9394** [comment]
> The number from your screenshots is valid in both https://laravel-phone.herokuapp.com/ and https://giggsey.com/libphonenumber/?phonenumber=0740169784&country=LK&language=&region=

But not work on this

**Comment by Propaganistas** [comment]
As @smares mentioned, that number works just fine.

![image](https://user-images.githubusercontent.com/6680176/120318830-9bf63980-c2e0-11eb-8299-b4e41e12afe3.png)

**Comment by ManojPrasha9394** [comment]
> As @smares mentioned, that number works just fine.
> 
> ![image](https://user-images.githubusercontent.com/6680176/120318830-9bf63980-c2e0-11eb-8299-b4e41e12afe3.png)

Number is correct but not validation work with Propaganistas/Laravel-Phone
other all numbers work fine

**Comment by Propaganistas** [comment]
In my book the sentence "Validation passes" means that validation works for this 74 XXX XXXX number.

**Comment by ManojPrasha9394** [comment]
> In my book the sentence "Validation passes" means that validation works for this 74 XXX XXXX number.

nope not work for 74 XXX XXXX 
other all sir Lankan numbers are working

**Comment by ManojPrasha9394** [comment]
$rules['contact_number'] = ['required', Rule::phone()->country(['LK'])];

**Comment by Propaganistas** [comment]
Please run `composer update`.

Dialog mobile numbers are available in libphonenumber 8.12.11 (October 9, 2020).
(https://github.com/giggsey/libphonenumber-for-php/releases/tag/8.12.11)

Current libphonenumber version is 8.12.24

**Comment by ManojPrasha9394** [comment]
My application build with laravel 6
So I install 4.2.2 version 
It their any effect ?

**Comment by ManojPrasha9394** [comment]
> Please run `composer update`.
> 
> Dialog mobile numbers are available in libphonenumber 8.12.11 (October 9, 2020).
> (https://github.com/giggsey/libphonenumber-for-php/releases/tag/8.12.11)
> 
> Current libphonenumber version is even at 8.12.24

Thanks After update composer work fine
