### ISSUE TITLE
Best way to validate E.164 phone numbers

### ISSUE THREAD

**Issue by dennisameling** [Propaganistas/Laravel-Phone#179]
We're currently building an application where we want to validate incoming phone numbers. Our frontend already converts phone numbers into E.164 format using the https://github.com/jackocnr/intl-tel-input library, so we just want to validate them on the Laravel side.

Since the standard [`phone` validator](https://github.com/Propaganistas/Laravel-Phone#validation) doesn't seem to have a way to validate E.164 phone numbers, we did it as follows:

```PHP
            'phone' => [
                'required',
                function ($attribute, $value, $fail) {
                    $phoneNumber = PhoneNumber::make($value);

                    if (!$phoneNumber->isValidFormat(PhoneNumberFormat::E164)) {
                        $fail('The field ' . $attribute . ' contains an invalid phone number. It has to be in the E.164 format (starting with +)');
                    }
                }
            ],
```

Would you be OK with me providing a PR to add E.164 validation to the default validator? If yes, please let me know if you have any preference for a specific syntax.

**Comment by Propaganistas** [comment]
Oh but the validator is surely capable of doing that. Just use the `AUTO` parameter.

https://github.com/Propaganistas/Laravel-Phone/blob/d85ce8af34d39afa39f96176c5ae645f0784e83c/tests/PhoneValidatorTest.php#L179-L183

**Comment by mattvb91** [comment]
@Propaganistas I am using the 'AUTO' validator but it still seems to fail for `+13251486005` when it was created with `$this->faker->e164PhoneNumber`. Any idea as to what it could be?

**Comment by Propaganistas** [comment]
Faker doesn't guarantee that generated numbers actually exist. That's just an invalid number.

![image](https://user-images.githubusercontent.com/6680176/125899776-ddba9306-c5c0-4c78-b29c-1c0ed385dd89.png)

**Comment by mattvb91** [comment]
aah I wasnt aware it actually does a check if they exist! That does make sense and is even better than what I expected! Thank you, appreciated!
