### ISSUE TITLE
Object of class Propaganistas\LaravelPhone\PhoneNumber could not be converted to int

### ISSUE THREAD

**Issue by mazraara** [Propaganistas/Laravel-Phone#180]
We are using this package for phone number validation however we ran into some strange behavior when we were trying to sort a collection where keys are id, uuid, name, mobile, phone.

Before installing this package we were able to sort by phone but as soon the package was installed it's creating this error.

How to reproduce?

```
                    $array = [
                        [
                            'id' => 1000001,
                            'uuid' => '00000000-0180-404c-b01a-7918f3d73f19',
                            'name' => 'AManual',
                            'mobile' => '3',
                            'phone' => '0094772343411',
                        ],
                        [
                            'id' => 1000002,
                            'uuid' => '22000000-0180-404c-b01a-7918f3d73f19',
                            'name' => 'XManual',
                            'mobile' => '2',
                            'phone' => '',
                        ],
                        [
                            'id' => 1000000,
                            'uuid' => '00000000-0180-404c-b01a-7918f3d73f19',
                            'name' => 'ZManual',
                            'mobile' => '1',
                            'phone' => '',
                        ],
                    ];

                    $collection = Collection::make($array);
                    $sorted = $collection->sortBy([['phone', 'desc']]);
                    return $sorted;
```
![image](https://user-images.githubusercontent.com/2024844/124700485-75907300-df0a-11eb-8202-6131a40078e9.png)

if you remove the package this works totally fine 

you can also try to sort with mobile while the package is installed and still it works fine.
`$sorted = $collection->sortBy([['phone', 'desc']]);`

**Comment by Propaganistas** [comment]
Your issue is unrelated to this package. You just cannot sort on objects. How does PHP know the position of an object with many properties? It can't.

Read the [documentation](https://laravel.com/docs/8.x/collections#method-sortby) of `sortBy` and take note of the closure-based definition.
