### ISSUE TITLE
The order of fields in the factory matters

### ISSUE THREAD

**Issue by osteel** [Propaganistas/Laravel-Phone#181]
Something really stupid just happened to me which I think should be documented.

When you use a factory for a model that has attribute casting from this package, make sure to fill in the country field _before_ the the phone number.

This:

```php
    /**
     * Define the model's default state.
     *
     * @return array
     */
    public function definition()
    {
        return [
            'phone_number'         => $this->faker->phoneNumber,
            'phone_number_country' => 'US',
        ];
    }
```

Will throw `Number requires a country to be specified`.

But this:

```php
    /**
     * Define the model's default state.
     *
     * @return array
     */
    public function definition()
    {
        return [
            'phone_number_country' => 'US',
            'phone_number'         => $this->faker->phoneNumber,
        ];
    }
```

Will work OK.

Also Faker won't always return a phone number that will be parsed as a US one, so you might want to implement something like [this](https://github.com/Propaganistas/Laravel-Phone/issues/73#issuecomment-817209431).

Not sure what you'll want to make of this issue, but feel free to close it.

**Comment by Propaganistas** [comment]
Thanks. I've made a note about this in the readme.
