### ISSUE TITLE
Not an issue, just wanted to say thanks

### ISSUE THREAD

**Issue by JonathanPort** [Propaganistas/Laravel-Phone#184]
Hi, 

I simply googled "validate phone number laravel" and clicked on the top repo. Came to this package, read through the very easy and clear docs and just appreciated how well made this library is, how it covers everything I need in order to make solid software that handles phone numbers correctly. I like how it's not "opinionated" and gives me all the tools I need to build my application my way. 

Thought I'd say many thanks for writing awesome code like this. You guys are legends 👍

**Comment by Propaganistas** [comment]
Thank you for your kind words!
