### ISSUE TITLE
German number with international prefix is not recognized without manually specifying the country

### ISSUE THREAD

**Issue by smares** [Propaganistas/Laravel-Phone#187]
https://giggsey.com/libphonenumber/index.php?phonenumber=004922199889988&country=GB&language=&region= recognizes the number as being valid from Germany. format() international prints +49 221 99889988.

https://laravel-phone.herokuapp.com/ says that validation failed for 004922199889988 and is not able to extract the country from the 0049 prefix on its own. Validation passes though, if you manually specify DE as language.

**Comment by Propaganistas** [comment]
https://giggsey.com/libphonenumber/index.php?phonenumber=004922199889988&country=GB&language=&region=

It shows that the number has a correct format (isValidNumber) but the number itself is actually invalid for region DE.

What is your expected validation result?

**Comment by Propaganistas** [comment]
Be careful with your first link. You're matching a German number to country GB. Also you should assess the result of `isValidNumberForRegion` and not `isValidNumber`.
 _(see what it did there? The number format itself, checked by `isValidNumber`, is deemed valid for GB!)_

Anyway, there's an important disclaimer in the validation section of the README:

> Note that country guessing will only work when phone numbers are entered in international format (prefixed with a + sign, e.g. +32 ....). Leading double zeros will NOT be parsed correctly as this isn't an established consistency.

That brings us to the following results:

```
number: 004922199889988
validation parameters: auto

--> Validation FAILS because of the disclaimer above.
```

```
number: +4922199889988
validation parameters: auto

--> Validation PASSES
```

```
number: 004922199889988
validation parameters: DE

--> Validation PASSES
```

**Comment by smares** [comment]
The link with GB was intentional to demonstrate the library didn't recognize the phone number as valid because I manually set the correct country. I did miss the comment in the documentation, though, sorry. Guess I can find a work-around with this info, thanks. 😄
