### ISSUE TITLE
Belgian landline number validation doesn't work

### ISSUE THREAD

**Issue by elimentz** [Propaganistas/Laravel-Phone#193]
It seems that the phone validation for Belgian numbers is wrong. The number below is a correct Belgian landline number but is marked as incorrect. 

https://giggsey.com/libphonenumber/?phonenumber=047625899&country=BE&language=&region=

**Comment by Propaganistas** [comment]
Hi

I'm afraid the number you provided is just invalid (I'm Belgian myself).

Your number : 047625899

* **04x** + 7 digits = landline phone range of Liège (Luik), but "x" can **only** be a 2 or a 3 while 7 is provided
* **047x** + 6 digits = mobile phone range of Proximus, but the provided number is 1 digit shorter

https://en.wikipedia.org/wiki/Telephone_numbers_in_Belgium
https://nl.wikipedia.org/wiki/Lijst_van_Belgische_zonenummers
