### ISSUE TITLE
Version 2.4.2 misfiring on Laravel 4.2

### ISSUE THREAD

**Issue by lucasatace** [Propaganistas/Laravel-Phone#20]
Hello,

Thank you for your work on this project. I have run into an issue when trying to integrate this with my site. When I attach the `phone` rule to my form. It seems to just continually return that it's in error, though I'm using my personal phone number. Please let me know what information you need from me and I will do all I can to help.

Thanks!

**Comment by lucasatace** [comment]
Update on this. I was using the `phone:AUTO` setting. I changed that to `phone:US` and that fixed the issue.

**Comment by Propaganistas** [comment]
Hi

I'm glad specifying the country manually fixed your problem for now.

Just as a follow-up: did you enter your personal phone number in international format when using `phone:AUTO`?

Note this paragraph in the readme:

> The validator will try to extract the country from the number itself and then check if the number is valid for that country. Note that this will only work when phone numbers are entered in international format (prefixed with a + sign, e.g. +32 ....). Leading double zeros will NOT be parsed correctly as this isn't an established consistency.

**Comment by lucasatace** [comment]
I had not tried that before, thank you for pointing this out.

I gave that a shot and it worked. Anyway that could default to the US code?

Either way, great piece of code here. Will definitely be using it again in the future.

Lucas R. Hibbard | Ace Ticket
Senior Web Developer
656 Beacon St. 2nd Floor | Boston, MA 02215
Phone: 617.586.1414

**Comment by Propaganistas** [comment]
Hardcoding a default is not viable however implementing a parameter to use as a default when in AUTO mode might be a good idea. I'll look into this when I have some time.

**Comment by Propaganistas** [comment]
I've rolled out a new release for this.
