### ISSUE TITLE
Laravel 7 conditionally validate if array

### ISSUE THREAD

**Issue by tschams** [Propaganistas/Laravel-Phone#203]
Is this possible, for example only validate that it is a valid phone number in the US, if it has 10 digits? I can use ```sometimes``` like this https://laravel.com/docs/7.x/validation#conditionally-adding-rules:~:text=%24v%2D%3Esometimes(%27,%7D)%3B, but can i do this if my data are arrays like ```"contacts.*.phone"```?

**Comment by Propaganistas** [comment]
In Laravel 8 a `Rule::when()` method has been introduced exactly for this. See https://github.com/laravel/framework/blob/004163a06fccd0e95fcd7f78989b6744b8f6325f/src/Illuminate/Validation/Rule.php#L20-L31

If you're on lower versions, you can always inline a conditional when defining your rules. No package magic needed here, just plain PHP:

```php
$rules = [
    'field' => strlen($value) === 10 ? ["phone:US"] : [],
];
```

or if you want to fail validation if not 10 digits use Laravel's built-in validations with "bail":

```php
$rules = [
    'field' => ["bail", "digits:10", "phone:US"],
];
```

**Comment by tschams** [comment]
Thank you @Propaganistas for responding! Yes, and for arrays I need to do something like the following helper function, which is not so clean. ```if (!function_exists("phoneValidations")) {
    function phoneValidations($data, $arrayKey, $valueKey)
    {
      $phoneValidation = [];
      foreach ($data as $i => $phoneNumber) {
        if (strlen($phoneNumber[$valueKey]) < 15) {
          $phoneValidation["$arrayKey.$i.$valueKey"] = [
            "nullable",
            "string",
            "max:255",
            "phone:US,CA",
          ];
        } else {
          $phoneValidation["$arrayKey.$i.$valueKey"] = [
            "nullable",
            "string",
            "max:255",
          ];
        }
      }
      return $phoneValidation;
    }
  }```

**Comment by tschams** [comment]
Thank you @Propaganistas for responding! Regarding ```$rules = [
    'field' => strlen($value) === 10 ? ["phone:US"] : [],
];```, I couldn't figure out how I can pass in ```$value``` according to the existing code. Therefore I ended up doing it not as clean as I would like with the following helper function. ```if (!function_exists("phoneValidations")) {
    function phoneValidations($data, $arrayKey, $valueKey)
    {
      $phoneValidation = [];
      foreach ($data as $i => $phoneNumber) {
        if (strlen($phoneNumber[$valueKey]) < 15) {
          $phoneValidation["$arrayKey.$i.$valueKey"] = [
            "nullable",
            "string",
            "max:255",
            "phone:US,CA",
          ];
        } else {
          $phoneValidation["$arrayKey.$i.$valueKey"] = [
            "nullable",
            "string",
            "max:255",
          ];
        }
      }
      return $phoneValidation;
    }
  }```
