### ISSUE TITLE
How to validate existing phone numbers

### ISSUE THREAD

**Issue by roarkmccolgan** [Propaganistas/Laravel-Phone#204]
Hi There,

Firstly, thank you for the package!

I would like to validate existing phone numbers, however can't see any methods like
```
PhoneNumber::make('number', 'country_code')->valid() // return true or false;
```

Is there a way to achieve this with this package?

Thank you!

**Comment by Propaganistas** [comment]
At this moment all validation logic is extracted out of the `PhoneNumber` class, so it's true there's no direct way.
However you could always instantiate a regular validator:

```php
validator(['number' => $number], ['number' => ['phone:'.$country]])->passes()
```

or create a macro method `isValid()` on the `PhoneNumber` class (it's macroable) that calls a validator on its own.

**Comment by roarkmccolgan** [comment]
Thank you!
Great to know
