### ISSUE TITLE
Error validating brazilian phone number

### ISSUE THREAD

**Issue by GersonAquino** [Propaganistas/Laravel-Phone#206]
I am trying to validate Brazilian phone numbers and I'm using this real number as an example +55 85 9934-6364, but I always get the same result "Validation failed".
I've tried it on https://laravel-phone.herokuapp.com/ with the country field BR, without it, and in the following formats:
+55 85 9934-6364
+558599346364
+55 85 99346364
+55859934-6364

![image](https://user-images.githubusercontent.com/58166147/194723373-99f4dc05-0b63-48ab-9a68-d9f19ce6e53a.png)

**Comment by Propaganistas** [comment]
Sorry, libphonenumber reports the number to be invalid. If you think this is wrong, please address your issue there: https://github.com/giggsey/libphonenumber-for-php

<img width="889" alt="Schermafbeelding 2022-10-09 om 16 13 09" src="https://user-images.githubusercontent.com/6680176/194761630-ae6f3812-e30c-4f82-8480-863d2949b6f2.png">
