### ISSUE TITLE
Serialization of exception may cause itself exception

### ISSUE THREAD

**Issue by idkCpp** [Propaganistas/Laravel-Phone#207]
When one parses a phone number that cannot be formatted to E164 because it is invalid, the resulting exception cannot be serialized, because serialization tries to convert to E164.

**Comment by Propaganistas** [comment]
Can you create a pull request suggesting a correction?

**Comment by idkCpp** [comment]
I do not fully understand why this serialization in https://github.com/Propaganistas/Laravel-Phone/blob/master/src/PhoneNumber.php#L447 happens.
I also do not have the time to work this out. So providing a pull request with a correction would probably not be very fruitful. I would just drop the serialization shebang or change it from formatE164 to just returning $number.

**Comment by Propaganistas** [comment]
Serializing an exception caused Laravel-Phone / libphonenumber will always trigger another exception because there's a Closure in the stack trace. At this moment I don't see any way out.
