### ISSUE TITLE
US phone number isn't being validated at all

### ISSUE THREAD

**Issue by sts-ryan-holton** [Propaganistas/Laravel-Phone#208]
I've just implemented this library into my project. I need a reliable way of ensuring mobile numbers are validated correctly. As per the docs, I'm sending my number in the E.164 format like so:

> +15558838530

I understand that the plus character can be stripped out, so I'm also encoding it in the request like:

> %2B15558838530

But when I try either variant in the demo https://laravel-phone.herokuapp.com/ page, it tells me that the number is invalid?

This is my rules: `phone:AUTO,GB` and my default is GB since I'll be sending from GB.

All my rules are:

```ppp
$validator = Validator::make($request->all(), [
    'phone' => [
        'required',
        'starts_with:+,%2B,(',
        'phone:AUTO,GB',
        new WithoutSpaces(),
        new StringLengthConstraints(7, 20)
    ],
    'message' => 'required|string|min:1|max:160',
    'key' => 'required',
    'sender' => 'nullable|min:2|max:160'
]);
```

Why is this invalid?

**Comment by Propaganistas** [comment]
Because the number is invalid according to libphonenumber.

![D7B275A6-15C3-453E-9D61-E008EBFE9F7D](https://user-images.githubusercontent.com/6680176/209675820-9ffce0cf-caa8-4da9-93dd-d6b8cc0596d4.jpeg)

**Comment by sts-ryan-holton** [comment]
@Propaganistas Thanks for the response. Is there any way to add any additional debugging to figure out what part is invalid? Or customise what functions are used to check the valid state? The possible number function returned true, so not sure why it would be detected as invalid?
