### ISSUE TITLE
Validation error

### ISSUE THREAD

**Issue by sevannerse** [Propaganistas/Laravel-Phone#209]
> Country Code: **AC**
> Phone Number: **+24762889**

It returned validation failed when I try to test over [herokuapp](https://laravel-phone.herokuapp.com/) with the above parameters. I have made the test with the same parameters at [libphonenumber's demo](https://giggsey.com/libphonenumber/index.php?phonenumber=%2B24762889&country=AC&language=&region=) and it passed. I think the countries should be parsed from the [supported regions](https://github.com/giggsey/libphonenumber-for-php/blob/f40e7696c207ec37465a9e841dd9d3b0a8e9c781/src/PhoneNumberUtil.php#L680) list of libphonenumber instead of the [thephpleague/iso3166](https://github.com/thephpleague/iso3166). That probably would solve the issue.

Please let me know if you're welcome a PR.

**Comment by Propaganistas** [comment]
Good catch. That'll remove a dependency as well. Please go forward with drafting a PR 👍
