### ISSUE TITLE
"Lenient" parameter implemented (code attached)

### ISSUE THREAD

**Issue by xfxf** [Propaganistas/Laravel-Phone#21]
Hi,

Please see:
https://github.com/xfxf/Laravel-Phone/commit/ec032305da681611ab2bac7b1e687526af867399

I added a parameter called "LENIENT" to expose more lenient phone number validation (in our case, area codes being optional) in the library you're relying on.

This code works; we're using it on a project right now.

I see you've refactored parts of this since the commit I based this off; I'm happy to update the code to reflect a PR against your latest commit, but probably be good to get feedback from you first.

**Comment by Propaganistas** [comment]
I'd be happy to merge the PR if its created against the current master
branch!

Thanks for your efforts!

**Comment by xfxf** [comment]
No worries, will do!
