### ISSUE TITLE
Number does not match the provided country. (NumberParse Exception)

### ISSUE THREAD

**Issue by HeadStudios** [Propaganistas/Laravel-Phone#212]
Running the following code:

```php
$mobile = PhoneNumber::make('+61463315544', 'AU')->formatE164();
    return $mobile;
```

Returns the following NumberParseException error:
'Number does not match the provided country.'

This is despite the format being a standard Australian international mobile format.

Any input or suggestions would be much appreciated.

Thank you!

**Comment by Propaganistas** [comment]
Please don't just skip the issue guidelines. Libphonenumber reports it to be invalid. 

The number has a correct syntactical format, but isn't valid according to carrier data.

![4D79E23D-ADD6-4AFA-8439-A5D437D38A25](https://user-images.githubusercontent.com/6680176/212736690-63fa2a4a-c9be-443c-99f4-5cfe36f36d79.jpeg)
