### ISSUE TITLE
Fails to validate international swedish numbers

### ISSUE THREAD

**Issue by iMusicJJ** [Propaganistas/Laravel-Phone#217]
We have a few internationally formatted phone-numbers that fails to validate.

We've only been made aware of it for swedish numbers, but it could be others.

A customer tried his phone number `+46704xxxxxx` and I tried a family members phone number `+46702xxxxxx`

Both fail the validation, despite me having first hand evidence that I can talk & sms with my family member at that last phone number.

**Comment by iMusicJJ** [comment]
Ohhh, I see.

So when you give the validation rule

`phone:auto` it works. But if you pass it the users country, which may not resonate with  their phone code. Eg. I am in Portugal w/ a danish phone. It fails.

- `phone:auto` work for both cases
- `phone:auto,DK` fails for both cases.

Why does it not fall back to auto, in case it isn't a proper DK number?

**Comment by Propaganistas** [comment]
Oh but it surely does...
See test below (it's a valid BE number).

https://github.com/Propaganistas/Laravel-Phone/blob/fd6dcd3b6368045af31bd1cc4d311d8f812b6522/tests/PhoneValidatorTest.php#L249-L253

Note: please also update to the newly released version (`5.x`). Be sure to check the release note for breaking changes.

**Comment by iMusicJJ** [comment]
Interesting, it doesn't seem to work in your own demo:

<img width="762" alt="image" src="https://user-images.githubusercontent.com/57725397/216089881-87b15a04-37cc-44e8-ae2e-5367a7c2c394.png">

**Comment by iMusicJJ** [comment]
Great. Confirmed fixed in 5.0.2.

Thanks
