### ISSUE TITLE
Dialing Codes

### ISSUE THREAD

**Issue by timbogdanov** [Propaganistas/Laravel-Phone#221]
This is not a bug, more of a feature request.

it would be nice if I could provide a country code like"

```php
    $code = PhoneNumber::getDialingCode('US'); 
```
and get back the dialing code in this instance a `+1`. A helper function would be great for this as well

**Comment by spburden** [comment]
Would be very nice indeed!

**Comment by Propaganistas** [comment]
The `PhoneNumber` class is macroable.
You could define a macro with the following callback:

```php
use libphonenumber\PhoneNumberUtil;

PhoneNumberUtil::getInstance()->getCountryCodeForRegion('US') // returns "1"
```

Or prepend a plus-sign if you need it like that.
The method's description mentions that unknown country codes will return 0.
