### ISSUE TITLE
Your demo site seems broken

### ISSUE THREAD

**Issue by carry2web** [Propaganistas/Laravel-Phone#222]
Prior to filing a bug, please check the origin of the unexpected behavior you're facing. Any issues that do not follow this guide will be closed without notice.

1. First try to reproduce the bug in the demo application (https://laravel-phone.herokuapp.com). If the bug cannot be reproduced here, go to step 2. Otherwise, you've possibly found a bug. Please go ahead and create an issue. Describe clearly what you're trying to achieve, along with some erroneous phone numbers and full validation parameters.

2. Try to reproduce the bug in libphonenumber's demo (https://giggsey.com/libphonenumber) and take note of the `isValidNumber()` and `isValidNumberForRegion()` results. Got unexpected or buggy behavior? Please open an issue at libphonenumber (https://github.com/giggsey/libphonenumber-for-php). If not, go to the next step.

3. This isn't a bug in the package nor in libphonenumber. Fix your own code.

**Comment by Propaganistas** [comment]
I'm aware of that. Heroku has dropped their free tier. The project is currently in review for their open-source platform program.
