### ISSUE TITLE
Validator fails on empty phone field, when required_if is present

### ISSUE THREAD

**Issue by MalteKiefer** [Propaganistas/Laravel-Phone#231]
Hello,

we use in our application the possibility to enter a phone number only, when a special value is selected in the dropdown:

```php
      request()->validate([
        'phone_mobile' => 'required_if:notificationchannelid,0|phone:DE,CH,AU',
        'pushoverkey' => 'required_if:notificationchannelid,1'
      ]);
```

The problem is, here, that the phone validator ignores this setting.
How can we set it up, that `phone` respects the `required_if`?

**Comment by Propaganistas** [comment]
I hate to say but I can't reproduce the issue you're facing.

```php
$data = ['notificationchannelid' => 0];

$validator = validator($data, [
    'phone_mobile' => ['required_if:notificationchannelid,0', 'phone:DE,CH,AU'],
]);

$validator->errors(); // The phone_mobile field is required when notificationchannelid is 0.
```

There must be something else going on in your code... For example: are you sure `notificationchannelid` is really "0"?
