### ISSUE TITLE
Validation for Lebanese mobile numbers starting with 78 fails

### ISSUE THREAD

**Issue by CyrilSleiman** [Propaganistas/Laravel-Phone#232]
Validation for mobile numbers in Lebanon (LB) works fine for all prefixes except 78 (+961 78 XXX XXX).

Here is a list of currently operational mobile number prefixes in Lebanon: 
03 (+961 3 XXX XXX) [Passes]
70 (+961 70 XXX XXX) [Passes]
71 (+961 71 XXX XXX) [Passes]
76 (+961 76 XXX XXX) [Passes]
78 (+961 78 XXX XXX) [Fails]
79 (+961 79 XXX XXX) [Passes]
80 (+961 80 XXX XXX) [Passes]
81 (+961 81 XXX XXX) [Passes]

References:
https://giggsey.com/libphonenumber/?phonenumber=78123123&country=LB&language=&region=
https://giggsey.com/libphonenumber/?phonenumber=%2B96178123123&country=LB&language=&region=

**Comment by Propaganistas** [comment]
Issue template ignored.

libphonenumber reports `isValidNumber()` to be invalid, so it's not a bug in this package.
