### ISSUE TITLE
When I used it, I found that the getCountryCode method was missing

### ISSUE THREAD

**Issue by zotopteam** [Propaganistas/Laravel-Phone#233]
version： [5.0.3]

When I used it, I found that the getCountryCode method was missing

`phone($phone)->getCountry()`  ok

`phone($phone)->getCountryCode()` bad

I can only use the following method, but it doesn't feel friendly, it is recommended to add this method

`phone($phone)->toLibPhoneObject()->getCountryCode()`

Thanks!

**Comment by Propaganistas** [comment]
The `PhoneNumber` class is macroable. You can create a macro if you want.
