### ISSUE TITLE
how do i use AUTO with the class interface?

### ISSUE THREAD

**Issue by jdion84** [Propaganistas/Laravel-Phone#237]
does this package have the ability to auto-detect country?

for example:

```php
$from = (new PhoneNumber($this->comm->from, 'AUTO'))->formatE164();
```

throws the error:

> Number does not match the provided country.

**Comment by jdion84** [comment]
nevermind im an idiot

**Comment by Propaganistas** [comment]
If the number is in international format, then yes. Just omit the country parameter when instantiating the object. 

In any other case, no. It's impossible to detect the exact origin of a number if you don't provide some countries to check against.
