### ISSUE TITLE
Extend checkCountries() to handle nested rule-sets

### ISSUE THREAD

**Issue by volkeransmann** [Propaganistas/Laravel-Phone#24]
Hi there,

just discovered that the Validator doesn't handle nested validation rules like:
address.phone
address.phone_country

Flatening the Array in line 126 of PhoneValidator.php with:
        $data = array_dot($validator->getData());
seems to fix the issue.

Maybe you can validate my findings and merge to master if correct.

Thanks,
volker

**Comment by Propaganistas** [comment]
Thanks for the report!
This small change indeed fixes the issue.
