### ISSUE TITLE
"mobile" parameter no longer working in 5.1.0 when one of the data fields is "mobile"

### ISSUE THREAD

**Issue by mwnciau** [Propaganistas/Laravel-Phone#241]
In [this commit](https://github.com/Propaganistas/Laravel-Phone/commit/99f2d320a15f1a7e5d196a3e8e17b586756ab44f#diff-48e28eb93ccfcade09cdb083d128c8a87e08516d3f2b182445f1877626f8bff9), the `mobile` and `fixed-line` string parameters were removed from `Phone::setParameters()`. This breaks backwards compatibility (so should be a major release) and I don't think is intended.

**Comment by mwnciau** [comment]
Upon further investigation, I realize that the functionality is being reproduced in the `type()` calls at the end. The issue I'm having is that because these calls have moved to the end, `$this->isDataKey($parameter)` on line 161 is returning true. I'm not sure what the function of that is, but the problem ultimately is that my form data field is "mobile", which makes it think it's a country.

**Comment by Propaganistas** [comment]
Continued in the linked PR
