### ISSUE TITLE
Laravel-Intl is unavailable

### ISSUE THREAD

**Issue by andrey-helldar** [Propaganistas/Laravel-Phone#245]
Hi! I apologize for writing here. I couldn't find any other method of contact.

The problem is that today we couldn't deploy one of our old projects on Laravel 5.6 because the [Laravel-Intl](https://github.com/Propaganistas/Laravel-Intl) package disappeared from GitHub.

We had to urgently pull it from the "vendor" folder of the test environment and place it in the application.

Is there any chance that this project will return to GitHub?

Thank you in advance for your reply.

![image](https://github.com/Propaganistas/Laravel-Phone/assets/10347617/45a84b57-38da-4b56-b3b2-0294ea896f8b)

**Comment by Propaganistas** [comment]
Hi

No it won't. The code is highly outdated and the package has been deprecated on packagist for 5 years already.

If you still need it, then you'll need to incorporate it in your application, or have composer autoload it by specifying a "repositories" entry in your composer.json file, using the "path" type.
```
"repositories": [
        {
            "type": "path",
            "url": "path/to/package/root"
        }
    ]
```

**Comment by andrey-helldar** [comment]
In my opinion, a very strange decision to delete even an old package. It would be better to move it to "archive" status on GitHub.

I was lucky that one of the test environments happened to have an application build with dependencies installed, because devops changes the server configuration and rebuilds containers. Today ran into a problem with a non-existent repository.

I can say that I was very lucky today.

Translated with DeepL.com (free version)
