### ISSUE TITLE
Laravel tripping the +

### ISSUE THREAD

**Issue by jamesmills** [Propaganistas/Laravel-Phone#247]
This isn't really a bug or an issue I'm just interested to know how others are dealing with this.

When I take an input from an API input for a phone number the actual input is "+447921220223" but when it goes through Laravel request it strips the "+" from the beginning so when I do something like `phone($phone)->getCountry()` it's not getting the country. If I hard code the phone value into this then it does get the country correctly.

How are people using the validation rule in Laravel and getting around this?

Thanks in advance,

James

**Comment by Propaganistas** [comment]
That's strange. I've never had any issues with that. How are you handling the incoming value? A phone number should be treated as a string. Perhaps you're casting it to a number, meaning that any non-numeric characters will be stripped automatically.

**Comment by webard** [comment]
GET request param can replace "+" sign to space in phone number, but you provide too little data.

**Comment by jamesmills** [comment]
Apologies to all.

I didn't provide enough information and it turns out it was simple enough that it was getting stripped because it was a GET request and the + was not URL Encoded.

I guess I thought using `phone($phone)->getCountry("+447921220223")` and `phone($phone)->getCountry("447921220223")` would both work but it looks like a number needs the `+` for the package to work.

I'll adjust my code. 

Thanks

**Comment by Propaganistas** [comment]
The + is a standardized prefix to denote international phone numbers. You could also swap the + with a country's [international call prefix](https://en.wikipedia.org/wiki/List_of_international_call_prefixes) (mostly used when calling from a landline phone).

Either a + or the international country prefix (00 for UK) is required to let carriers know that the first few digits (44 in your example) point to a country, followed by the actual number.

So both **+44**7921220223 and **0044**7921220223 will work, while **44**7921220223 lacks an international pointer.
