### ISSUE TITLE
Warning: Loaded on every request

### ISSUE THREAD

**Issue by FelixMalfait** [Propaganistas/Laravel-Phone#25]
Maybe you should add a disclaimer to warn people that this package is loaded on every request, along with the packages it requires itself like Translation, causing a significant slowdown of runtime.

Many people just need this on a few pages, in that case they would probably be better off with a simple regex or with an adaptation of your package to handle autoloading more efficiently.

Anyway, thanks for sharing!

**Comment by Propaganistas** [comment]
Hi there

I'm not quite sure I understand your reasoning. The package registers itself in two ways: defining a singleton binding in the container and defining a validator. Both are only resolved as soon as they're needed, which is only the case when Laravel's Validator tries to parse a phone validation rule. In addition the translation is just one extra line in an already existing file that is loaded anyway.
So in fact on pages where the validator isn't needed the only thing this package does is adding an entry to an array.

When compared to some other packages this can even be considered as a lightweight one in my opinion...

In any case I'll be glad to review any benchmarks you can provide.
