### ISSUE TITLE
Invalid number format passes validation

### ISSUE THREAD

**Issue by ravensborn** [Propaganistas/Laravel-Phone#252]
Hello,

Trying to validate a number with symbols appended to the end will pass the validation as a valid number.

Case:
- Input: `+9647507534867-----++$%^`
- Laravel validation: `['required', 'string', 'distinct', 'phone:IQ']`.

Demo Application:

Issue also present in demo application.

![image](https://github.com/Propaganistas/Laravel-Phone/assets/27031143/fa83de9c-a611-4137-b615-75f3956f324e)

libphonenumber's demo (This library might filter out the input before checking for the number validity):

- `isPossibleNumber()`: true
- `isValidNumber()`: true
- `isValidNumberForRegion()`: true

**Comment by Propaganistas** [comment]
As you showed yourself libphonenumber is reporting that string to be a valid phone number string - and I'd bet it does so on purpose. Please redirect your issue to that repository or apply additional validators checking the input's format
