### ISSUE TITLE
Custom validation messages for different phone types

### ISSUE THREAD

**Issue by OrakFR** [Propaganistas/Laravel-Phone#253]
Hi,

First of all, thank you for the excellent package! It has been very helpful in our project.

I have a question regarding the validation messages for different phone types. In the documentation, I see that we can specify the allowed types for phone numbers in the validation rule, like so:

```php
'cellphone_number' => 'nullable|phone:mobile|...',
'phone_number' => 'nullable|phone:fixed_line|...',
```

Is there a way to define custom validation messages that target the different allowed types?

For instance, instead of displaying the same validation error message regardless of the type, I would like to show a more user-friendly message specific to the type of phone number being validated.

For example:

- For **mobile** numbers: "The phone number must be a valid mobile number."
- For **fixed_line** numbers: "The phone number must be a valid fixed line number."

I've tryied different rules combinations in the `validation.php` but it didn't work:

```php
    'mobile' => [
        'phone' => 'The :attribute field must be a valid mobile number.',
    ],
```
```php
    'phone' => [
        'mobile' => 'The :attribute field must be a valid mobile number.',
    ],
```
or even
```php
    'phone.mobile' => 'The :attribute field must be a valid mobile number.',
```

If this is possible, could you please provide some guidance or an example on how to achieve this?

Thank you in advance for your help!

**Comment by Propaganistas** [comment]
What you're asking is unsupported by Laravel out of the box. But you could use custom rule objects to achieve what you're looking for.

Wrap the `phone` validator as you desire. Or even create multiple rule objects. Be creative.

https://laravel.com/docs/11.x/validation#using-rule-objects

```php
class MobilePhone implements ValidationRule
{
    public function validate(string $attribute, mixed $value, Closure $fail): void
    {
        $validator = validator([$attribute => $value], [$attribute => 'phone:mobile']);

        if ($validator->fails()) {
            $fail('The :attribute must be a mobile phone.');
        }
    }
}
```
