### ISSUE TITLE
pass validation for invalid number

### ISSUE THREAD

**Issue by Kareem-Ayman** [Propaganistas/Laravel-Phone#254]
my validation rule ( phone:SA,EG )

test by this : null01046587921

![Capture](https://github.com/Propaganistas/Laravel-Phone/assets/40733188/b8ad6f38-b171-4a38-8ad4-83bc5b039706)

**Comment by Propaganistas** [comment]
See https://github.com/Propaganistas/Laravel-Phone/issues/252#issuecomment-2105013208
