### ISSUE TITLE
Why would you delete the repository `propaganistas\laravel-intl`

### ISSUE THREAD

**Issue by OzanKurt** [Propaganistas/Laravel-Phone#255]

**Comment by Propaganistas** [comment]
The code in there was highly outdated and the package marked as deprecated on Packagist **for 5 years already**. Plenty of time to move away from it.

If you still need it, then you'll need to retrieve a copy somewhere, incorporate it in your application, or have composer autoload it by specifying a "repositories" entry in your composer.json file, using the "path" type.

"repositories": [
        {
            "type": "path",
            "url": "path/to/package/root"
        }
    ]
