### ISSUE TITLE
Ivory Coast Validation Failure

### ISSUE THREAD

**Issue by gostavo9911** [Propaganistas/Laravel-Phone#258]
### Laravel-Phone version

4.4

### Reproducible Laravel-Phone demo URL

https://laravel-phone.herokuapp.com/?parameters=phone%3A&phone=%2B22507014657

### Reproducible libphonenumber demo URL

https://giggsey.com/libphonenumber/?phonenumber=%2B22507014657&country=IV&language=&region=

### Additional remarks

the phone number is +2250701xxxx which is for ivory coast mobile and it's a valid number but the library doesn't detect it

**Comment by Propaganistas** [comment]
Libphonenumber reports the number to be invalid. Please redirect your issue to there.
