### ISSUE TITLE
Hungarian number is formatted in NATIONAL wrongly

### ISSUE THREAD

**Issue by sandu2d** [Propaganistas/Laravel-Phone#259]
### Laravel-Phone version

5.3.0

### Steps to reproduce

Use magic function:
`phone("+36 70 510 4452", "HU", \libphonenumber\PhoneNumberFormat::NATIONAL)`
Result:
`"6705104452"`

### Observed vs Expected behavior

Result of:
`phone("+36 70 510 4452", "HU", \libphonenumber\PhoneNumberFormat::NATIONAL)`
should be:
`"705104452"`

Is wrong because after if I try to convert back with:
`phone("6705104452", "HU", \libphonenumber\PhoneNumberFormat::E164)`
it will throw error:
`"Number does not match the provided country"`

but with:
`phone("705104452", "HU", \libphonenumber\PhoneNumberFormat::E164)`
will work, also tested on validation demo pages.

**Comment by Propaganistas** [comment]
Hi

this output of formatting is returned directly from libphonenumber like this.
https://giggsey.com/libphonenumber/?phonenumber=%2B36+70+510+4452&country=hu&language=&region=

![image](https://github.com/user-attachments/assets/a1e70e3e-a82c-4a3e-92a6-d4692ed47001)

Please create an issue over there if you think the output is wrong.
--> https://github.com/google/libphonenumber

**Comment by Propaganistas** [comment]
I can see though that `"6705104452"` does not match `"06 70 510 4452"`.
Apart from spaces being stripped, it's missing the leading zero.

Are you sure you don't apply additional formatting to that value?
`"6705104452"` can never be the direct output of `phone("+36 70 510 4452", "HU", \libphonenumber\PhoneNumberFormat::NATIONAL)`

**Comment by sandu2d** [comment]
@Propaganistas  The issue was on my side. I did a trim of 0 before saving and that brake the conversion from NATIONAL to INTERNATIONAL. I thought is OK as it worked with other countries.
Thank you for leading the info about crucial 0
