### ISSUE TITLE
Benin 10-digit number validation update

### ISSUE THREAD

**Issue by pmt-nauhand** [Propaganistas/Laravel-Phone#261]
### Laravel-Phone version

5.3.2

### Steps to reproduce

1. Configure the Propaganistas/Laravel-Phone package for phone number validation.
2. Set Benin (+229) as the target country.
3. Attempt to validate a 10-digit number, for example: 2290191234567.

### Observed vs Expected behavior

**Expected Behaviour**
Benin phone numbers should accept 10 digits according to the new regulations.

**Actual Behaviour**
The package limits Benin phone numbers to 8 digits, making it impossible to validate a 10-digit number.

**Suggested Solution**
Update the package's phone number validation rules to align with the current regulations for Benin, which now accepts 10-digit numbers. The first digit is 01

**Comment by Propaganistas** [comment]
this is not a bug but an unexpected validation result.
Please follow the guidelines over [there](https://github.com/Propaganistas/Laravel-Phone/issues/new?assignees=&labels=&projects=&template=01-validation.yml).
