### ISSUE TITLE
Empty Country Field

### ISSUE THREAD

**Issue by EvilLooney** [Propaganistas/Laravel-Phone#29]
Hi,

I have a problem when receiving an empty value for a country code. The InvalidParameterException error is thrown but it should not be the case.

I think on line 114 of PhoneValidator.php, the line should be:
`if (!is_null($this->isInputField($parameter))) {`

Does that seem right?

Thanks.

**Comment by Propaganistas** [comment]
Hi, I just tried myself but unfortunately I cannot reproduce your issue. I'm getting the NoValidCountryFoundException.

Can you please elaborate? E.g. paste the validator rule, `var_dump` the empty value, ...

**Comment by EvilLooney** [comment]
Hi,

I should specify that the phone field should not be empty for this to happen.

The `$parameters` variable in the `assignParameters` function gives me this:
```
array (size=1)
  0 => string 'country' (length=7)
```

The validator rule is:
```
[
    'country' => 'required_with:phone|in:' . $countryList,
    'phone' => 'required_with:country|phone:country'
]
```
... where $countryList is a comma-separated list.

**Comment by Propaganistas** [comment]
I was able to reproduce now and have fixed the issue. Thanks for reporting.
