### ISSUE TITLE
problem parsing validation since 2.7

### ISSUE THREAD

**Issue by corbosman** [Propaganistas/Laravel-Phone#30]
I used to have the following validation rule:
```
'mobile'      => 'phone:NL,mobile',
```

As of 2.7 this no longer works as you check if the 'mobile' parameter is the input field, which in this case it is, and starts to assume I will have a custom_country_field. 

Of course easily fixed by changing the name of the form field to something other than mobile, but imo this still is a bug as the form field name should have no consequences.

**Comment by Propaganistas** [comment]
Nice catch. Please update to `^2.7.4`, it should be fixed in there.
