### ISSUE TITLE
fixed_line_or_mobile

### ISSUE THREAD

**Issue by strebl** [Propaganistas/Laravel-Phone#31]
Hi,

Thanks for making this library!

Maybe it's a configuration error on my side, but if I use the "fixed_line_or_mobile" number constraint, all numbers are invalid.

```php
$this->validate($request, [
    'phone_number' => 'required|phone:CH,fixed_line_or_mobile',
])
```

But if I use booth everything works as expected (mobile and fixed_line numbers are valid):

```php
$this->validate($request, [
    'phone_number' => 'required|phone:CH,fixed_line,mobile',
])
```

Did I miss something?

**Comment by Propaganistas** [comment]
Hi

There's a minor misconception about the `fixed_line_or_mobile` constraint. That type is only assigned if the number type could not be detected (see https://github.com/giggsey/libphonenumber-for-php/blob/master/src/libphonenumber/PhoneNumberType.php#L12), in all other situations the correct type will be assigned by liphonenumber.

As such, if you want to validate that a number is a fixed line or mobile, just use the `fixed_line` and `mobile` constraints as suggested in your second code snippet.

By the way: no need to handle the edge case `fixed_line_or_mobile` manually; the validator will add that constraint automatically when applicable (https://github.com/Propaganistas/Laravel-Phone/blob/master/src/PhoneValidator.php#L212).

**Comment by strebl** [comment]
Thanks @Propaganistas for your help and the fast reply!
