### ISSUE TITLE
Validation inside a request object?

### ISSUE THREAD

**Issue by jpmurray** [Propaganistas/Laravel-Phone#33]
Hello,

I've used the validation rule perfectly while using the validation request inside a controller, but now that I'm moving said rules under their own requests object (`artisan make:request`), the `phone:Country` validation rule doesn't seems to work.

Is there anything I should do to make it work there?

**Comment by Propaganistas** [comment]
It should just work over there (I'm using it constantly in Request objects). Please provide more context (logs, request pipeline, debug info, ...)
