### ISSUE TITLE
[Laravel 5.2] phone_format throws exception

### ISSUE THREAD

**Issue by computerfr33k** [Propaganistas/Laravel-Phone#35]
I have the following code in laravel, but no matter what I do, it always throws an exception.
Exception:
`NumberParseException in PhoneNumberUtil.php line 1348:
Missing or invalid default region.`
```php
Route::get('/sms', function() {
    return phone_format('2025550115');
});
```

**Comment by Propaganistas** [comment]
The README clearly states the following:

> `phone_format($phone_number, $country_code = null, $format = PhoneNumberFormat::INTERNATIONAL)`
> Format a fetched phone value using the helper function. $country_code is the country the phone number belongs to.
> **If no $country_code was given, the current application locale will be used as default.** 

It seems that your application locale (EN perhaps?) does not match with the corresponding country code for the phone number you're providing (US ?). Try to explicitly supply the country code in the helper function to resolve this, eg.: 

```php
Route::get('/sms', function() {
    return phone_format('2025550115', 'US');
});
```
