### ISSUE TITLE
problem with belgian fixed line phone number for area 04

### ISSUE THREAD

**Issue by AlexandreBeauduin** [Propaganistas/Laravel-Phone#38]
Hi,

phone validation (phone:BE) fails with this number : +32 4 799 70 15
but works if I add a number at the end
or with those one : +32 4 199 70 15 - +32 4 299 70 15 - +32 4 399 70 15

to resume:

works if 
- first digit after +32 4 is 1, 2 or 3 
- if I add a number at the end (thus entering mobile phone number ;) )

fails if
- first digit after +32 4 is 0,4,5,6,7,8,9

Can you please correct this? :)

Thanks a lot,

pudeldoodle

**Comment by Propaganistas** [comment]
Hi there.

I'm living in Belgium myself. The Belgian phone number search engines [1207 (Flemish)](http://www.1207.be/047997015/onbekend/onbekend/onbekend/no_result) or [1307 (Walloon)](http://www.1307.be/047997015/inconnu/inconnu/inconnu/no_result) both return a not found notice. Are you sure this is an existing number? Seems rather odd to me that 04 is followed by a 7 for a fixed line; this is a starting pattern of a mobile phone number...

If you still think this is a valid number, please redirect your issue to [libphonenumber](https://github.com/giggsey/libphonenumber-for-php) as this package is merely a Laravel wrapper.

**Comment by AlexandreBeauduin** [comment]
Hi there,

Hello from Brussels then ;)

Actually it is a wrong number I was given... 
The best part is that it is actually a mobile phone number missing a number :'/

Thanks for the support and thanks for the validator!

pudeldoodle
