### ISSUE TITLE
PhoneNumberUtil::getInstance() throwing The phone number supplied was null.

### ISSUE THREAD

**Issue by stav3ng3r** [Propaganistas/Laravel-Phone#40]
Hello,

When using the LaravelPhoneFacade or anytime I use PhoneNumberUtil::getInstace() in the consctructor of a Controller I'm getting a:
PHP Fatal error:  Uncaught Error type: 1. The phone number supplied was null. thrown in PhoneNumberUtil.php on line 1376

This happens when I run artisan route:list for example.

**Comment by Propaganistas** [comment]
Please show some code. The error you're experiencing is unrelated to the facade or `PhoneNumberUtil::getInstance()`. Possibly you're running the `parse()` method without any arguments.
