### ISSUE TITLE
libphonenumber-for-php v8 released

### ISSUE THREAD

**Issue by giggsey** [Propaganistas/Laravel-Phone#43]
Hi,

[libphonenumber-for-php v8](https://github.com/giggsey/libphonenumber-for-php/releases/tag/8.0) has been released, and it'll be good for this project to support it going forwards.

The BC changes are:
 - Convert from PSR-0 to PSR-4
 - Remove deprecated `ShortNumberUtil`, use `ShortNumberInfo` instead
 - Deleting deprecated methods in `ShortNumberInfo` that work on strings, instead
   of phone number objects. These have been marked deprecated for months. Any
   users of these methods should call `PhoneNumberUtil::parse` first to create a
   `PhoneNumber` object, and pass this in.
 - Support semicolon as extension character while parsing phone numbers.

**Comment by anewmanjones** [comment]
I have created a PR #42 which upgrades to v8 as well as some fixes for phpunit warnings.

**Comment by Propaganistas** [comment]
Thanks for the heads-up!
