### ISSUE TITLE
Manually validate phones

### ISSUE THREAD

**Issue by loranger** [Propaganistas/Laravel-Phone#44]
Hello,

I'd like to validate phone numbers I already have in my database, in order to fix the wrong ones.

How can I achieve this ?
I can't figure out how to call `isValidNumber` manually.

Can you help, please ?

**Comment by Propaganistas** [comment]
Hi

Just use the `phone` validator as a regular Laravel validator. It isn't any different from default Laravel practices.

```php
use Validator;

$value = '0123456789'; // Fetch value from database
$validationRule = 'phone:US'; // Configure as explained in this package's documentation

$validator = Validator::make(['value' => $value], ['value' => $validationRule]);

if ($validator->fails()) {
    // Incorrect phone number...
}
```

I suggest you review Laravel's [documentation on Validation](https://laravel.com/docs/master/validation) thoroughly.

**Comment by loranger** [comment]
Thank you so much.

I was trying to use `Propaganistas\LaravelPhone\PhoneValidator` manually but the solution was simplier, indeed.

Thanks again, for this package and your support
