### ISSUE TITLE
In Laravel 5.4, it is throwing the error instead of returning as validation failure message

### ISSUE THREAD

**Issue by karmendra** [Propaganistas/Laravel-Phone#47]
Basically, my validation rule is defined as `$rules = ['mobile_number'=>'required|phone:IN,mobile']`
when the input is 
1. +919900990099 - validation passes
2. +919900 - I validation failed with error message `The mobile number field contains an invalid number.`
3. +919 - I get exception
> NumberParseException in PhoneNumberUtil.php line 1477: The string supplied is too short to be a phone number.
4. when empty value is passed - I get exception
>NumberParseException in PhoneNumberUtil.php line 1381: The phone number supplied was null.

I am expecting the Exception messages to be returned as validation error messages.

Hope reporting the issue help improving this lovely package.

**Comment by Propaganistas** [comment]
Hi

That's odd, as there's a try/catch block catching that exception.
I tried it myself with your example data and rules, but unfortunately I cannot reproduce this.

Please provide more context.

**Comment by Propaganistas** [comment]
FYI, this is my test code on a fresh Laravel 5.4:

```php 
$data = [
    'field1' => '+919900990099',
    'field2' => '+919900',
    'field3' => '+919',
    'field4' => null,
];

$rules = [
    'field1' => 'required|phone:IN,mobile',
    'field2' => 'required|phone:IN,mobile',
    'field3' => 'required|phone:IN,mobile',
    'field4' => 'required|phone:IN,mobile',
];

dd(Validator::make($data, $rules)->errors());
```

**Comment by karmendra** [comment]
Thanks, for your response, I will do more debugging in my code to see what exactly is causing this.
I had installed this package in two of my projects, one was on Laravel 5.1 and another one on Laravel 5.4, It is working as expected in L5.1 but it is still behaving the same in my L5.4 project.

**Comment by karmendra** [comment]
Sorry for the confusion, it was my codes issue, it was not the validation but phone number formatting throwing this exception. 
`$input['mobile_number'] = phone($input['mobile_number'], $country_code = 'IN', $format = PhoneNumberFormat::E164);`

**Comment by adifaidz** [comment]
Hi, I think it is throwing an exception, I have these two usage in my class but when I commented the call to format, it still throws the exception.

#### The call to format
```php
$phone_number = ltrim(PhoneNumber::make($arguments[0], 'MY')->formatE164(), '+');
```

#### But when I commented them both, finally it went silent.
```php
$argument = ['phone_number' => $arguments[0]];
$rule = ['phone_number' => 'phone:MY'];
$validator = Validator::make($argument, $rule);
if($validator->fails()) //Exception is thrown here
    //Do something
```

**Comment by Propaganistas** [comment]
Can you paste the value of `$argument[0]` please?

**Comment by Propaganistas** [comment]
@adifaidz Please update to 3.0.1 and start a new issue when the problem persists.

**Comment by adifaidz** [comment]
Confirmed, working with 3.0.1 thanks!
