### ISSUE TITLE
Upgrade to newer libphonenumber

### ISSUE THREAD

**Issue by marabooyankee** [Propaganistas/Laravel-Phone#5]
Hi  could you update the version of the libphonenumber referenced in composer.json.
A new version 7.* is out and although I haven't tested it, I don't think it breaks backwards compatibility.

Keep up the good work :+1: .

**Comment by Propaganistas** [comment]
Done. Please update to version 1.2.0.
See https://github.com/Propaganistas/Laravel-Phone/tree/1.2.0

**Comment by marabooyankee** [comment]
Thanks man :+1: 

Sent from my windows phone 

-----Original Message-----
