### ISSUE TITLE
Validation Errors trying every format.

### ISSUE THREAD

**Issue by Drakota** [Propaganistas/Laravel-Phone#53]
I'm doing form request validation and I tried using this package, but I can't seem to get it working, my validation looks like this : 
```
<?php

namespace App\Http\Requests\Users;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Contracts\Validation\Validator;

class UserCreatePost extends FormRequest
{
    public function authorize()
    {
        return true;
    }

    public function rules()
    {
        return [
          'email' => ['required', 'email', 'unique:users'],
          'first_name' => ['required'],
          'last_name' => ['required'],
          'phone' => ['required', 'phone:CA', 'unique:users'],
        ];
    }

    protected function formatErrors(Validator $validator)
    {
        var_dump($validator->attributes());
        throw new StoreResourceFailedException('Could not create new user.', $validator->errors());
    }
}
```
I get 
```
{
    "message": "Could not create new user.",
    "errors": {
        "phone": [
            "The phone field contains an invalid number."
        ]
    },
    "status_code": 422
}
```
I tried different format : 
+1 123 456 7890
+1-123-456-7890
+1 (123) 456 7890
+1 (123) 456-7890
(123) 456-7890
+11234567890
Not working.
I added `Propaganistas\LaravelPhone\LaravelPhoneServiceProvider::class,` in my $providers.

Thanks for helping.

**Comment by Propaganistas** [comment]
Other online phone validators such as [here](https://numverify.com), [here](http://www.phonevalidator.com) and [here](https://www.textmagic.com/free-tools/phone-validator) are also reporting that the number is invalid, so the error returned by the package is probably correct: the number is simply invalid.

**Comment by Drakota** [comment]
Oh, alright I just though it checked format not validity.

**Comment by vahidalvandi** [comment]
$data = $request->all();
            $data['mobile'] = (string)phone($data['mobile'], $data['mobile_country']);

            $messages = [
                'mobile.required' => 'ورود شماره موبایل الزامی است',
            ];

            $rules = [
                'mobile' => ['required', 'phone', 'unique:users'],
                'mobile_country' => ['required_with:mobile'],
            ];

            $validator = Validator::make($data, $rules, $messages);
