### ISSUE TITLE
Formatting with "auto-discovery"

### ISSUE THREAD

**Issue by keptdream** [Propaganistas/Laravel-Phone#55]
Hello, I'd like to use the formatter like the validator with auto-discovery and fallback countries

phone($phone_number, $country_code = "AUTO,CH,...", $format = PhoneNumberFormat::INTERNATIONAL)

So, I want to store fomatted phone numbers in my database without using the "country" field. Because I already have a country field in my database and I also use it as last fall-back method. And I don't want to annoy or confuse any people by asking the country again. It would be a very nice addition.

**Comment by keptdream** [comment]
Sorry, could not wait. I created pull request for this issue: 
https://github.com/Propaganistas/Laravel-Phone/pull/56
Hope that this will work.

**Comment by Propaganistas** [comment]
Thanks for the suggestion. Seems like a nice addition indeed. Will implement this in the next few days.

**Comment by Propaganistas** [comment]
The requested feature is available in v3.0.0

Please be weary of the breaking changes when updating (see the [release note](https://github.com/Propaganistas/Laravel-Phone/releases/tag/3.0.0)).

**Comment by keptdream** [comment]
Thank you!
