### ISSUE TITLE
international mobile no start with 00

### ISSUE THREAD

**Issue by musman92** [Propaganistas/Laravel-Phone#57]
'xxxxx => 'required|phone:AUTO,US,AE'
now i use validation rule like this and it works fine with +(country code)(mobile no)

but requirement is instead of +9 start with 00 
how i can do this

**Comment by Propaganistas** [comment]
See this line in the README:

> Note that country guessing will only work when phone numbers are entered in international format (prefixed with a + sign, e.g. +32 ....). Leading double zeros will NOT be parsed correctly as this isn't an established consistency.

As a workaround you could check and convert the input, e.g.:

```
if(starts_with($number, '00')) {
    $number = substr_replace($number, '+', 0, 2);
}

// Now perform your validation...
```

**Comment by musman92** [comment]
thank you @Propaganistas
