### ISSUE TITLE
InvalidParameterException

### ISSUE THREAD

**Issue by keptdream** [Propaganistas/Laravel-Phone#58]
Hello, I have a problem with dev-3.0

I can't use this validation string anymore:

> 'phone_number' => 'required|phone:AUTO,CH,country',

this is fine:

> 'phone_number' => 'required|phone:AUTO,country',

this is also fine:

> 'phone_number' => 'required|phone:AUTO,country',

Where **country** is a select field with your other LaravelIntl library.

It did work with the older version.

The error:
```
(1/1) InvalidParameterException
Invalid phone validation parameters: "CH".


in InvalidParameterException.php (line 17)
--
at InvalidParameterException::parameters(object(Collection))in Phone.php (line 122)
at Phone->extractParameters('phone_number', array('AUTO', 'CH', 'country'), array('_token' => '***', '_method' => 'PATCH', 'title' => '***', 'old_customer_number' => null, 

...more fields...

 'country' => 'CH', 'phone_number' => '+41 ****')in Phone.php (line 47)
at Phone->validate('phone_number', '+41 ****', array('AUTO', 'CH', 'country'), object(Validator))
```

I censored the number with ****

So basically I can't use AUTO, Fallback Country AND Fallback secondary field.
(Also tested where Fallback country and Fallback field are different)

Main reason why I don't want to use a dedicated country field for phone number because I don't want to confuse customers with problaly "unnecessary" fields. Because most of our customers live in Switzerland and will most likely have a Swiss phone number anyway. But if not then I wan't to fallback to "their" country just for the sake of convenience. And if this does not pass I'll show an error, where they will be asked to add the country code to their number. I mean, I can leave this as is and only use one hardcoded country field... Or use the country as a fallback country... But this method seems the most convenient to me and it did work before... Maybe... At least it did not throw an error. :D
I hope you understand what I mean.

Am I doing something wrong here? Is it a bug? Is there a better way of doint things?

**Comment by Propaganistas** [comment]
Thanks for reporting. I've added a few tests in order for this to be covered in future releases.

Please update to `3.0.2` to get the desired behavior.
