### ISSUE TITLE
custom output format

### ISSUE THREAD

**Issue by huglester** [Propaganistas/Laravel-Phone#59]
Hello,

I was wondering. This lib is really nice for validation.
But for example I need an output format like:

+1.123456
so in general:
+COUNTRY_CODE then PERIOD then PHONE NUMBER.

Does this library allows this?

**Comment by Propaganistas** [comment]
No. The library only supports the standardized formats defined [here](https://github.com/giggsey/libphonenumber-for-php/blob/master/src/PhoneNumberFormat.php).

To achieve the format you're looking for you could further process the international format:

```php
use Propaganistas\LaravelPhone\PhoneNumber;

$number = PhoneNumber::make('123456', 'US')->formatInternational();
// preg_replace exchanges the first space (which will always be after the country calling code),
// then str_replace removes all other spaces.
$number = str_replace(' ', '', preg_replace('/ /', '.', $number, 1));
```
