### ISSUE TITLE
"propaganistas/laravel-phone": "~1.2" results in error.

### ISSUE THREAD

**Issue by ziming** [Propaganistas/Laravel-Phone#6]
Using "propaganistas/laravel-phone": "~1.2" in composer.json led to errors. I wonder if that is because it is not publicly marked as a version at 

https://packagist.org/packages/propaganistas/laravel-phone

Where the latest stable listed is version 1.1

Using "propaganistas/laravel-phone": "dev-master"

fixes the problem.

**Comment by vinkla** [comment]
It seams like the version `1.2.0` isn't registered in the [packagist registry](https://packagist.org/packages/propaganistas/laravel-phone). @Propaganistas does the package auto-update on packagist?

**Comment by Propaganistas** [comment]
That's odd! Auto-updating was set up correctly.
Anyhow, I force-updated the package on Packagist and it should work now.
As an attempt to avoid any future problems I also re-initialized the auto-update service.

Thanks for reporting.

**Comment by vinkla** [comment]
Great! I've had similar problems with Packagist before. Never found out why.
