### ISSUE TITLE
Validation issue

### ISSUE THREAD

**Issue by athiteshkubavat** [Propaganistas/Laravel-Phone#63]
I think there might be a problem with validation. I want to write validation for phone number ( for ex. +91 12345674890) and it works fine but the problem is whenever a user enters any two characters after a mobile number (for ex. +91(1234567891) bd ) it treats as a valid phone number. Please give me appropriate solution.

Thanks in advance.

**Comment by Propaganistas** [comment]
It seems the underlying library [libphonenumber](https://github.com/googlei18n/libphonenumber) just accepts the number you referenced. [Try it](http://rawgit.com/googlei18n/libphonenumber/master/javascript/i18n/phonenumbers/demo-compiled.html) yourself.

Please open an issue over there, or strip the alpha characters before validation if you don't like them.
