### ISSUE TITLE
Eloquent mutator of phone cause the model isDirty always return true

### ISSUE THREAD

**Issue by duongtdvn** [Propaganistas/Laravel-Phone#64]
I have the `phone` attribute on `User` model which currently use this package for phone formatting via Eloquent mutator and accessor like so

`User` Model
```php
public function getPhoneAttribute($value)
{
    return phone($value)->formatForCountry('VN');
}

public function setPhoneAttribute($value)
{
    return $this->attributes['phone'] = phone($value, 'VN');
}
```
While perfoming update request to the controller **with no changes** the phone attribute still getting updated with same attribute. This occur even if the `getPhoneAttribute` method removed.

UserController
```php
public function update(UpdateProfileRequest $request)
{
    $request->user()->update($request->all());
    return redirect()->back();
}
```

So it seem that the Model is know the phone attribute has been dirtied even if it is not?

**Comment by Propaganistas** [comment]
By using the `phone` helper you're essentially creating a new object each
time the mutator is invoked, resulting in the model being marked as dirty.

If you would like to retain the mutator you should serialize the phone
object (which happens to be its string representation):

```php
public function setPhoneAttribute($value)
{
    $this->attributes['phone'] = serialize(phone($value, 'VN'));
}
```

Op 12-okt.-2017 12:09 PM schreef "Duong Truong" <notifications@github.com>:

**Comment by Propaganistas** [comment]
```php
public function setPhoneAttribute($value)
{
    $this->attributes['phone'] = serialize(phone($value, 'VN'));
}
```

**Comment by duongtdvn** [comment]
I'm getting this error while using your comment
```sql
SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'phone' at row 1 (SQL: update `users` set `phone` = C:38:"Propaganistas\LaravelPhone\PhoneNumber":12:{+84888333998}, `updated_at` = 2017-10-12 20:38:29 where `id` = 1)
```

**Comment by Propaganistas** [comment]
Please think about it yourself for a second: the column length is too short. As a workaround you could directly cast it to a string:

```php
public function setPhoneAttribute($value)
{
    $this->attributes['phone'] = (string) phone($value, 'VN');
}
```
