### ISSUE TITLE
Problems with `GB` number [v3.0.3]

### ISSUE THREAD

**Issue by arubacao** [Propaganistas/Laravel-Phone#65]
```
Psy Shell v0.8.14 (PHP 7.1.11 — cli) by Justin Hileman

>>> $number = phone('447937947973', 'GB');
=> Propaganistas\LaravelPhone\PhoneNumber {#907}
>>> $number->getCountry();
Propaganistas\LaravelPhone\Exceptions\NumberParseException with message 'Country specification for number "447937947973" required.'

>>> $number = phone('12252280247', 'US');
=> Propaganistas\LaravelPhone\PhoneNumber {#935}
>>> $number->getCountry();
=> "US"
```

What am I doing wrong?

**Comment by Propaganistas** [comment]
`GB`, which I presume stands for Great Britain, isn't a valid country code. Great Britain is not considered a country; it's the "main" island of the United Kingdom. See [Wikipedia](https://en.wikipedia.org/wiki/Great_Britain).

The correct country code is `UK`.

**Comment by arubacao** [comment]
> The correct country code is `UK`

Sounds good, doesn't work:
```
Psy Shell v0.8.14 (PHP 7.1.11 — cli) by Justin Hileman
>>> $number = phone('447937947973', 'UK');
=> Propaganistas\LaravelPhone\PhoneNumber {#909}
>>> $number->getCountry();
Propaganistas\LaravelPhone\Exceptions\NumberParseException with message 'Country specification for number "447937947973" required.'
```

According to the standards [CLDR version 32.0.0](http://cldr.unicode.org/index/downloads), [iso3166](https://en.wikipedia.org/wiki/ISO_3166-1#Officially_assigned_code_elements) and also your main dependencies [giggsey](https://github.com/giggsey/Locale/blob/1.4/data/en.php#L91), [julien-c](https://github.com/julien-c/iso3166/blob/43d97b80c16bf0162f36b90111da0edfe215e009/src/Codes.php#L248) `GB` is the only valid representation for `United Kingdom`.
> The United Kingdom is officially assigned the alpha-2 code GB rather than UK, based on its official name "United Kingdom of Great Britain and Northern Ireland"

Furthermore, this method call `phone('447937947973', 'GB', \libphonenumber\PhoneNumberFormat::INTERNATIONAL)` works with version `2.8.5` of your library, but fails with `3.0.3`.

Cheers,
Chris

**Comment by Propaganistas** [comment]
I was taking a hard guess there.

Another one, but once again, just off the top of my head, untested:
--> the number you're trying to parse starts with `44`
--> the parser has been rewritten (hence the major version difference). It now works like this:
* If a plus sign is encountered, the number is considered in international prefix and the country can be guessed automatically. 
* If not, the number will be parsed using the country provided.

Since `+44` is the international phone prefix for UK numbers, but you're supplying a number starting with `44`, the parser thinks `44` is part of the actual number in **national** format.

Prefix the number with a plus or leave out the 44?

**Comment by arubacao** [comment]
The US number works without the + prefix 
```
>>> $number = phone('12252280247', 'US');
=> Propaganistas\LaravelPhone\PhoneNumber {#935}
>>> $number->getCountry();
=> "US"
```
With the + prefix for the GB numbers, I now see an unexpected "country" `JE` (Jersey)
```
>>> $number = phone('+447937947973', 'GB');
=> Propaganistas\LaravelPhone\PhoneNumber {#953}
>>> $number->getCountry();
=> "JE"
>>> $number = phone('+447937947973');
=> Propaganistas\LaravelPhone\PhoneNumber {#990}
>>> $number->getCountry();
=> "JE"
```

**Comment by arubacao** [comment]
I ended up solely using `giggsey/libphonenumber-for-php` with a simple replacement method. All my tests are green now.
```
    /**
     * Format the phone number to an international format.
     *
     * @param string $number
     * @param string $country
     * @return string International number
     * @throws \libphonenumber\NumberParseException
     */
    private function formatNumber(string $number, string $country): string
    {
        $phoneNumberUtil = \libphonenumber\PhoneNumberUtil::getInstance();
        $phoneNumberObject = $phoneNumberUtil->parse($number, $country);
        return $phoneNumberUtil->format($phoneNumberObject, \libphonenumber\PhoneNumberFormat::INTERNATIONAL);
    }
```

I'm pretty confident, that `propaganistas/laravel-phone:3.0.3` should behave the same like `propaganistas/laravel-phone:3.0.3` and the above method `formatNumber` for this call: `phone('447937947973', 'GB', \libphonenumber\PhoneNumberFormat::INTERNATIONAL)`.

Cheers,
Chris

**Comment by Propaganistas** [comment]
It seems you stumbled upon an edge bug, but nonetheless important one: while JE is considered part of GB (as it should), version 3 simply rejected the supplied country if it didn't match the number's actual one. I've implemented a small enhancement to still check out the provided country, as it might be coupled to the actual one, just like the case JE / GB.

Thanks for reporting and insisting on this.

BTW: The number we're debugging really is a Jersey number. So libphonenumber will always return JE as the country code.

**Comment by arubacao** [comment]
Cool that you provided a fix that fast & glad I could help.
I wasn't aware that the number is a `JE` number since the only thing I actually needed was the internationally formatted number :)
