### ISSUE TITLE
Is Laravel-Phone Working Properly

### ISSUE THREAD

**Issue by dukesnuz** [Propaganistas/Laravel-Phone#66]
This does not validate 1112224444, sometimes
This does valadate 111-aaa-4444, sometimes
This does validate 111-222-4444, sometimes

Using Laravel 5.5.21

**Comment by dukesnuz** [comment]
Think I figured it, maybe, So the Laravel-Phone actually verifies area codes?

**Comment by Propaganistas** [comment]
I'm highly reluctant about the "sometimes" part in your post. A number is either valid or invalid... It all depends on the supplied validation parameters.

Please directly check `libphonenumber` using [this](https://giggsey.com/libphonenumber/index.php) demo and look out for the `isValidNumber()` and `isValidNumberForRegion()` results. I presume `US` is the corresponding country code. Both the demo and the package are reporting those numbers are incorrect.

If you would like further assistance, please paste relevant code snippets.
