### ISSUE TITLE
v3.0.4 Laravel 5.5 validation

### ISSUE THREAD

**Issue by lancasterlad** [Propaganistas/Laravel-Phone#71]
Laravel 5.5 validation rule of 'phone:GB' is validating as though it is a required field. If the field is empty it is still validating.

**Comment by Propaganistas** [comment]
Seems like an issue with Laravel itself as the same is true for any other built-in Validator when you pass a `null` into the validator:

```php
use Validator;

Validator::make(['test' => null], ['test' => 'integer'])->passes();
// FALSE - "Field test must be an integer"

Validator::make(['test' => ''], ['test' => 'integer'])->passes(); 
// TRUE (rule is ignored as it should)
```

Please raise this in Laravel's issue tracker. In the meantime you can work around this behavior by allowing the field to be nullable: `'field' => 'nullable|phone:GB'`.
