### ISSUE TITLE
does not play well with faker

### ISSUE THREAD

**Issue by jpuck** [Propaganistas/Laravel-Phone#73]
I sporadically get validation errors when testing using factories created by [Faker][faker].

For example, given this factory:

```php
$factory->define(App\Contact::class, function (Faker $faker) {
    return [
        'phone' => $faker->phoneNumber,
    ];
});
```

and this validation rule:

```php
public function rules()
{
    return [
        'phone' => 'phone:AUTO,US',
    ];
}
```

It will work most of the time, but sometimes builds will fail due to generated examples like this:

> (590) 908-1660 x233

It seems to be failing to validate any extension that isn't explicitly 4 digits. So `x1234` is valid, but `x123` and `x12345` will fail.

Please advise on the best way to handle this situation. Is it that non-4-digit extensions are truly invalid, or maybe that the `AUTO` detection is getting in the way?

[faker]:https://github.com/fzaninotto/Faker#fakerprovideren_usphonenumber

**Comment by Propaganistas** [comment]
It seems `libphonenumber` (the underlying validation library) is validating this number to false (see [here](http://libphonenumber.appspot.com/phonenumberparser?number=%28590%29+908-1660+x233&country=US)).

I'm not familiar with detailed specifications either, so please direct your enquiry to [libphonenumber](https://github.com/googlei18n/libphonenumber).

**Comment by jpuck** [comment]
Thanks @Propaganistas for your quick response!

**Comment by JoshMoreno** [comment]
Quick solution for Laravel 8, which introduced class-based factories.

In your factory:
```
public function validPhoneNumber(): string
{
    $result = null;

    do {
        $fakePhone = $this->faker->phoneNumber;
        try {
            PhoneNumber::make($fakePhone, 'US')->formatE164();
            $result = $fakePhone;
        } catch (\Exception) {
        }
    } while ( ! $result);

    return $result;
}
```

Consider moving this to a trait if you need it in multiple factories.
