### ISSUE TITLE
Method [validatePhone] does not exist.

### ISSUE THREAD

**Issue by adamsow** [Propaganistas/Laravel-Phone#74]
Hello,
I followed the installation instructions and added all needed validation but have this error when submitting the form:

> (1/1) BadMethodCallException
> Method [validatePhone] does not exist.
> in Validator.php (line 1110)
> --
> at Validator->__call('validatePhone', array('myPhone', null, array('PL'), object(Validator)))in Validator.php (line 352)
> ...

Any idea what may be the cause? I'm using laravel 5.4
Propaganistas\LaravelPhone\PhoneServiceProvider::class added to providers list.
Validation in request:
 'myPhone' => 'phone:PL',

Thanks in advance!
Regards,
Adam

**Comment by Propaganistas** [comment]
Are you're sure you're on the latest version (`3.0.4`)?

**Comment by adamsow** [comment]
Hi,
I just run the composer require propaganistas/laravel-phone command.

In my composer.json i can see:
"propaganistas/laravel-phone": "^3.0",

Regards,
 Adam

**Comment by Propaganistas** [comment]
Since `Illuminate\Validator` is complaining about an unknown method, it seems the `PhoneServiceProvider isn't registered (properly).

**Comment by adamsow** [comment]
OK, reinstallation and clear-compiled helped.
Thanks for your support and for laravel phone!
Regards,
Ada,

**Comment by mateuszanella** [comment]
For future reference: the same issue seemed to be caused by bootstrap cache, thus not registering the service provider. Dumping that seemed to have fixed this issue.
