### ISSUE TITLE
InvalidParameterException is thrown when country_code is invalid, instead of failing the validation

### ISSUE THREAD

**Issue by juampi92** [Propaganistas/Laravel-Phone#77]
Hi. Awesome plugin. I've encountered the following issue:

When you use an invalid phone_country code on the validation rule, it breaks, instead of returning invalid fields. My code is the following

````php
$attrs = request()->validate([
       'phone_country'  => 'required_with:phone|string|size:2',
       'phone'          => 'phone:phone_country'
]);
````

When I make a request with the following body:
````js
[
    'phone' => '555555555',
    'phone_country' => 'A'
]
````

Instead of returning invalid and the reason being something like 'That :attribute is not a valid country code', it throws:

`Propaganistas\LaravelPhone\Exceptions\InvalidParameterException: Invalid phone validation parameters: "A".`

I don't consider this a big deal though. I don't think my users are going to misuse the phone_country field, and I could errorHandler that exception, but I think you might be interested on knowing that.

**Comment by juampi92** [comment]
I think [this](https://github.com/Propaganistas/Laravel-Phone/issues/70) issue was stating my same problem...

Maybe it's a laravel thing, but laravel tries to validate every field to gather as much errors as possible, so I think that's why it's failing.

And another thing, if the `phone_country` uses an invalid (a string, size 2 but not in the list of possible countries), it'd fail with the same exception.

I understand that that exception is useful when validating the ->country() property, but when it's the ->countryField(), besides validating the Front End, there's nothing we can do.

**Comment by Propaganistas** [comment]
Thanks for reporting. I now understand the issue clearly. Fixed!

**Comment by Propaganistas** [comment]
New release `3.1.0` rolled out.

**Comment by EdgarSedov** [comment]
Same problem occurs when i try to use Rule::phone()->countryField('country')
