### ISSUE TITLE
Unique Phone Validation & Formats

### ISSUE THREAD

**Issue by dror3go** [Propaganistas/Laravel-Phone#80]
Hi,

I have an application which aims for a single country, and have a unique `phone` column in a table.
I would like to add a uniqueness validation on the column, as well as making sure that the phone is valid in the country. My problem is when trying to take into consideration various formats of the phone when it's being created by the end user.

To overcome this issue, I've created a `FormatPhone` middleware which extends `Illuminate\Foundation\Http\Middleware\TransformsRequest` and transforms the request's phone to the desired format.
It seems to work fine, only thing is that in case of a validation failure due to phone uniqueness issue - the `old('phone')` value no longer holds the actual phone string as was typed by the user, but rather a formatted version of it. I can live with that, but was wondering - do you have a different approach for such a thing?

Thanks!

**Comment by Propaganistas** [comment]
A uniqueness constraint on a database column holding a phone number seems rather weird to me, but anyway, the combination of such constraint and preformatting makes this a peculiar case to tackle.

I'm afraid the only (easy) way is to copy over the phone's value to a temporary variable, format it, merge it in the request and validate on that one. That way the old request value is left untouched.

```php
$formattedPhone = phone($request->input('field'), $country, $format);
$request->merge(['_field' => $formattedPhone]);
$request->validate(['_field' => 'phone|unique']);
```

**Comment by dror3go** [comment]
@Propaganistas What makes you say that such a uniqueness is weird? I'm willing to listen :)
Say an app that authenticates users with a phone number, or the ability for admins to add clients in a CRM - you don't want multiple users/clients with the same phone number.

**Comment by Propaganistas** [comment]
Fair point.

You could also just provide a modified data array to the validator instead of modifying the request variable.

```php
$data = $request->all();
$data['field'] = phone($data['field'], $country, $format);

$this->validate($data, ['field' => 'phone|unique']);
```

**Comment by megawubs** [comment]
We also need to have unique phone numbers in our system because users are able to login by mobile phone. 

Now i'm trying to apply your suggestion above, but this fails when the provided value is `null` because a `null` value cannot be formatted, thus an exception is thrown.

For now i've created an custom rule called `UniquePhone`. This is used in combination with the `phone` rule. Idealy i would like to be able to inline this with the `Rule::phone()` call.

This is what I have now:

```php
public function test_validation_fails_when_phone_is_invalid_and_should_be_uniqe(): void
{
        $validator = validator(
            ['phone' => '99182810198'],
            ['phone' => [Rule::phone()->country('NL')->mobile(), new UniquePhone(table: 'users')]]
        );

        $this->assertTrue($validator->fails());
}

```
Idealy I would like to be able to do something like this:

```php
public function test_validation_fails_when_phone_is_invalid_and_should_be_uniqe(): void
{
        $validator = validator(
            ['phone' => '99182810198'],
            ['phone' => [Rule::phone()->country('NL')->mobile()->unique('users')]]
        );

        $this->assertTrue($validator->fails());
}

Do you think this is possible to add?

```

**Comment by Propaganistas** [comment]
@megawubs What you're aiming for is only syntactical sugar. The "[unique](https://laravel.com/docs/9.x/validation#rule-unique)" rule exists and Laravel's validator feature is designed to chain multiple validation rules.

```php
$rules = [
    'phone' => [
        Rule::phone()->country('NL')->mobile(),
        Rule::unique('users'), // or 'unique:users'
    ]
];
```

You'll want to format the phone number before persisting to the database, and then apply the same formatting when checking for uniqueness.
