### ISSUE TITLE
GB, UK Validation not working

### ISSUE THREAD

**Issue by Aiwe30** [Propaganistas/Laravel-Phone#82]

**Comment by Propaganistas** [comment]
If you expect to receive support you might want to take some effort yourself by including some example numbers and culprit code.

**Comment by Propaganistas** [comment]
Please also check if you can reproduce your "bug" in the demo: https://laravel-phone.herokuapp.com/

**Comment by Aiwe30** [comment]
Hi, the numbers: 
+44 1632 960218 and 01632 960218 
numbers comes from this website:   https://fakenumber.org/united-kingdom
And I tried to enter a real number that I'm using, still won't work.

Validation in my app is simple 
'number' => 'required|phone:GB,US,IE,AU,NZ,LT,LV,EE,CA'
Everything working fine except GB, 

Tried UK, have an error message: "Invalid phone validation parameters: "UK"."

Tried in your app: Laravel Phone demo (3.1.0) have result:
FAILED
{
  "number": [
    "The number field contains an invalid number."
  ]
}

**Comment by Propaganistas** [comment]
First of all:

> [...] all generated UK telephone numbers are indeed 100% non-working. [...] whilst these random phone numbers will not be assigned for use by telephony companies in the foreseeable future [...].

Libphonenumber checks the validity of phone numbers, even their existence. So the numbers generated at fakenumber.org will **never** validate to true.

Secondly:
> And I tried to enter a real number that I'm using, still won't work.

See my first answer: no details = no support. `GB` is the correct country code for the United Kingdom by the way. Check your "real" number in [libphonenumber's demo](https://giggsey.com/libphonenumber) and look out for the `isValidNumber()` and `isValidNumberForRegion()` results.

**Comment by Aiwe30** [comment]
Thank You for the answer. That answer I'm waiting for, because in this fake number website, US, AU, CA numbers are passing validation, I had problem only with UK phone numbers. Now searched and checked valid phone numbers and they are ok. Thank you for the answer, and sorry for your time.
