### ISSUE TITLE
Non required phone field validation

### ISSUE THREAD

**Issue by ghost** [Propaganistas/Laravel-Phone#84]

**Comment by MattWohler** [comment]
@AceWT how did you get around this? Seems like I'm having the same issue. My DB field is nullable as well as the first rule on the field.

**Comment by AceWT** [comment]
Hi, you have to add nullable param like this:

```php
$this->validate($request,[
  'phone_phone' => 'nullable|phone:AUTO,HR,fixed_line',
]);
```

**Comment by MattWohler** [comment]
Thanks @AceWT

The error I was getting was actually due to another issue. I am using an Accessor/Mutator on the field which was making the assumption that the `$value` actually exists!
