### ISSUE TITLE
Local phone numbers pass, internationally formatted numbers don't

### ISSUE THREAD

**Issue by Ziadjb** [Propaganistas/Laravel-Phone#85]
When we try to validate a 9 numbers phone number, eg. 056475896 OR 56475896 it passes.
But, when I try it with the country telephone code eg +3356475896, or +3456475896, or +156475896, or +21256475896, it does not pass. Why?

056475896 or 56475896 should be an invalid phone number format

---
phone:FR,ES,MA,US,BE accept 9 numbers format without telephone code

**Comment by Propaganistas** [comment]
056475896 is a valid Belgian phone number. Since you configured that the phone number can belong to either one of those six countries (including Belgium), the validator passes.
