### ISSUE TITLE
AU validation fails with 0453... and 0454...

### ISSUE THREAD

**Issue by EddyTheDove** [Propaganistas/Laravel-Phone#87]
The bug was reproduced in the demo application.
Tried mobile phone `0454231278` and `0453231278` with the country `AU`. It fails as an invalid number.

Actually none of these work
41, 42, 43, 45, 46, 53, 54, 60, 61, 62, 63, 64, 65, 71, 80, 83, 86, 92, 93, 94, 95, 96

**Comment by Propaganistas** [comment]
The issue template clearly asks to check your number first in
libphonenumber's demo..

Anyway: `libphonenumber` reports the number is invalid, so please redirect
you issue to [giggsey/libphonenumber-php](
https://github.com/giggsey/libphonenumber-php).

[
https://giggsey.com/libphonenumber/?phonenumber=0454231278&country=AU&language=&region=](https://giggsey.com/libphonenumber/?phonenumber=0454231278&country=AU&language=&region=)
