### ISSUE TITLE
Not working until add to provider

### ISSUE THREAD

**Issue by mohamedsabil83** [Propaganistas/Laravel-Phone#89]
First, thank you for the valuable package.

I install it in Laravel5.6 and works like charm in local. But, when uploading to my hosting, I need to add it to the provider section in **config/app** or it returns an error as shown in attached picture.
![screenshot from 2018-07-02 22-02-00](https://user-images.githubusercontent.com/10126040/42181484-ab5b2a32-7e43-11e8-970f-2b848af948f1.png)

**Comment by Propaganistas** [comment]
If auto-discovery is working locally then there's something sketchy going on in your live environment and I'm afraid it's unrelated to this package. 

Some thoughts:
* Are you sure you got the **same** Laravel version installed? 
* Try the following command: `php artisan package:discover`
* How about other packages that should be auto-discovered?

**Comment by mohamedsabil83** [comment]
- **Are you sure you got the same Laravel version installed?**
Yes, I'm working with **Laravel5.6** and latest package version **4.0.2**

- **Try the following command: php artisan package:discover**
I did it and it has shown with the list.

- **How about other packages that should be auto-discovered?**
All other packages work normally without needing to add their provider to **config/app** file.

**Comment by Propaganistas** [comment]
I'm afraid I can't reproduce. I got several applications running this package on different hosting providers without any problems, and also a freshly spinned up instance runs just fine... For some reason or the other the service provider isn't registered in your environment.

In any case, this shouldn't pose a problem. Just add the Service Provider in `config/app.php` as you mentioned. If the provider is already registered by auto-discovery the additional line will just be ignored and won't be registered twice.

**Comment by mohamedsabil83** [comment]
Yes, I did that and it works like a charm. Just inform you to check if it was a bug.
