### ISSUE TITLE
LaravelPhone\NumberParseException should cover all parse exceptions

### ISSUE THREAD

**Issue by IntraCherche** [Propaganistas/Laravel-Phone#91]
Hi,

Great code! Would it be possible to only throw Propaganistas\LaravelPhone\Exceptions\NumberParseException for all parse exceptions.

Eg : if I parse 010203+0608  in FR I get a libphonenumber\NumberParseException when Propaganistas\LaravelPhone\Exceptions\NumberParseException was expected!

Keep up the good work

**Comment by Propaganistas** [comment]
The package's NumberParseException directly extends libphonenumber's
NumberParseException and is merely a convenience wrapper for common
exception messages. You should always catch the one from libphonenumber.

Op di 17 jul. 2018 06:32 schreef IntraCherche <notifications@github.com>:

**Comment by IntraCherche** [comment]
Got it! Thanks Propaganistas your answer is helpful.
