### ISSUE TITLE
registerValidator() failing silently

### ISSUE THREAD

**Issue by lehelkeresztes** [Propaganistas/Laravel-Phone#92]
I'm using Laravel 5.5 and I noticed something very strange.
in `PhoneServiceProvider` within the function `registerValidator()` is this line:
`$this->app['validator']->{$extend}('phone', Validation\Phone::class . '@validate');`

this doesnt' work for me, it just failed silently, no validation, nothing.
to test, I've changed this line within this file to:
`Validator::extendDependent('phone', Validation\Phone::class . '@validate');`  and now it everything works! (both extend and extendDependent work).

I've no idea why this is happening, but i thought i'd raise it to your awareness. Feels free to close it if you think it's from my instance.

**Comment by Propaganistas** [comment]
Very strange. I'm indeed afraid there's something odd about your Laravel app or even PHP. However I can't pinpoint the exact problem; it's quite bizarre it just fails silently...

**Comment by lehelkeresztes** [comment]
Thanks for the reply. I ended up writing my own service provider with your code, just that one line changed and now it works fine. I've no idea either why.
