### ISSUE TITLE
Validator fails when there is empty telephone field

### ISSUE THREAD

**Issue by gileneusz** [Propaganistas/Laravel-Phone#93]
Making very simple validator:
 
```
$validator = Validator::make($request->all(), [
'telephone' => 'phone:PL'
]);
```

this makes validator fails - with empty telephone field,

Validator should fail when 
`'telephone' => 'required|phone:PL'`
rule is given

it should pass -> when there is empty telephone field and `'phone:PL'` rule only

imho

what if my user has a choice to write telephone or not? Then I can't use `phone:PL` rule

**Comment by Propaganistas** [comment]
Please read [Laravel's documentation regarding validators](https://laravel.com/docs/5.6/validation#a-note-on-optional-fields):

> By default, Laravel includes the `TrimStrings` and `ConvertEmptyStringsToNull` middleware in your application's global middleware stack. These middleware are listed in the stack by the `App\Http\Kernel` class. Because of this, you will often need to mark your "optional" request fields as nullable if you do not want the validator to consider null values as invalid. For example:
> ``` php
> $request->validate([
>     'title' => 'required|unique:posts|max:255',
>     'body' => 'required',
>     'publish_at' => 'nullable|date',
> ]);
> ```
> In this example, we are specifying that the publish_at field may be either null or a valid date  representation. If the nullable modifier is not added to the rule definition, the validator would consider null an invalid date.

--- 

You're describing the very same scenario: mark your field `nullable` if it shouldn't validate if it's present in the request and could possibly be empty.

**Comment by gileneusz** [comment]
sure, this is the way it should be
