### ISSUE TITLE
Can't catch ParseNumberException

### ISSUE THREAD

**Issue by Efrain177** [Propaganistas/Laravel-Phone#97]
![captura de pantalla 2018-12-03 a la s 11 28 39](https://user-images.githubusercontent.com/32506049/49396867-c8c13a00-f6ff-11e8-8d98-f000ea9def7d.png)
Hello im doing the following block of code

```
try {
            $phone = PhoneNumber::make($phone);

        } catch (\libphonenumber\NumberParseException $exception) {
            $response['message'] = 'Invalid phone number';
            return $response;

        }
```

And the try catch is not catching the Exception, any ideas?

**Comment by Propaganistas** [comment]
The stack trace shows use of `PhoneNumber::getCountry()` reach the error, while the code you provided never calls this method. So there's another part of your code responsible for hitting the error.

It could be one of the following:
* Getting the type of a phone number using `getType()`
* Getting the country of a phone number using  `getCountry()`
* Formatting a phone number using a `formatXXX()` method

**Comment by Efrain177** [comment]
Im afraid that the line :
`$phone = PhoneNumber::make($phone);`
Is the responsible for hitting the error since no where else in my code im using the library.

I am aware that PhoneNumber::make asks for a country code, thats why I wanted to try catch it so if in any weird case that the validation fails I can assurance that the controller wont crash.

Anyways, so my best shoot should be what Stanislass suggested and fully trust the validation?

**Comment by Propaganistas** [comment]
Well, on my behalf I'm confident that `PhoneNumber::make()` really doesn't hit `getCountry()` in any way.

A `formatXXX()` method also gets called when you cast a `PhoneNumber` to a string.

Just navigate down the Whoops error page to see where the responsible code is located...

**Comment by Efrain177** [comment]
![captura de pantalla 2018-12-03 a la s 13 30 00](https://user-images.githubusercontent.com/32506049/49396787-96afd800-f6ff-11e8-8fcf-db616886f8b4.png)

Just double checked and apparently the function make doest hit ofCountry()

**Comment by Propaganistas** [comment]
`ofCountry()` != `getCountry()`

Please follow my advice and check the trace:
> navigate down the Whoops error page to see where the responsible code is located...

**Comment by Efrain177** [comment]
Alright, I Kinda found the error, for some reason the trait Auditable from Laravel-Auditing is conflicting with the PhoneNumber::make function.

Thank you for your patience.

**Comment by michiel-inovamedia** [comment]
I guess this bug got ignored? I too cannot catch the exception. The content of the exception doesn't matter. I need to catch it, not show it to the user.

**Comment by Propaganistas** [comment]
This bug was addressed. See https://github.com/Propaganistas/Laravel-Phone/blob/master/src/PhoneNumber.php#L390

If you're still experiencing issues, it's unrelated.
